"""Auto-updating phone dashboard — today's WNBA plays, served free via GitHub Pages.

Reads the injury-autobetter ledger (wnba_ledger.sqlite) and renders a mobile HTML page to
docs/index.html, grouped by beneficiary (team logo + name), sorted most-confident first.
Tap a bet to expand a PropsCash-style bar chart of the player's game-by-game results in
the role, with the line drawn and each game colored over/under. Regenerated by the WNBA
workflows, served by Pages, self-refreshing — current on your phone, no Mac.

    python dashboard.py            # -> docs/index.html
"""
from __future__ import annotations

import datetime as dt
import html
import json
import sqlite3
from collections import defaultdict
from pathlib import Path

import requests

try:
    from zoneinfo import ZoneInfo
    MT = ZoneInfo("America/Denver")            # user-local, for DISPLAY times only
    ET = ZoneInfo("America/New_York")          # the slate day + pred_date basis, for DATE filters
except Exception:
    MT = dt.timezone(dt.timedelta(hours=-6))
    ET = dt.timezone(dt.timedelta(hours=-4))

HERE = Path(__file__).resolve().parent
FRESH_MIN = 90     # best-price: only quotes re-posted within this many min of the newest count as live
LEDGER = HERE / "wnba_ledger.sqlite"
OUT = HERE / "docs" / "index.html"
STAT = {"points": "PTS", "rebounds": "REB", "assists": "AST",
        "pra": "PRA", "pts_reb": "P+R", "pts_ast": "P+A", "reb_ast": "R+A"}
STATKEY = {"points": "pts", "rebounds": "reb", "assists": "ast",
           "pra": "pra", "pts_reb": "pts_reb", "pts_ast": "pts_ast", "reb_ast": "reb_ast"}
THIN_EV = 0.35
LOGO = "https://a.espncdn.com/i/teamlogos/wnba/500/{}.png"

# ---- LIVE bar recompute ----------------------------------------------------------------------
# The dropdown bars are recomputed FRESH on every dashboard build from current game logs + the
# current out-set — so a change to bar logic (or a game just played) shows up on the next rebuild
# instead of waiting for the alert to re-log the frozen `samples` snapshot. Falls back to the stored
# samples on any lookup/fetch failure, so the dashboard never hard-depends on the network.
_GLOG_TTL = 1200                                   # 20 min: a 60s dashboard loop won't refetch each build
_GLOG_FILE = HERE / "wnba_gamelog_cache.json"
_glog_mem = {}
_glog_disk = None


def _name2id():
    try:
        d = json.loads((HERE / "wnba_players_cache.json").read_text())
        return {n: v.get("id") for n, v in d.get("players", {}).items() if v.get("id")}
    except (OSError, ValueError):
        return {}


NAME2ID = _name2id()


def _glog(pid):
    """A player's game log, cached in-process + on disk with a TTL. Returns the stale copy (or [])
    if the fetch fails, so the dashboard degrades to stored samples instead of breaking."""
    global _glog_disk
    if pid in _glog_mem:
        return _glog_mem[pid]
    if _glog_disk is None:
        try:
            _glog_disk = json.loads(_GLOG_FILE.read_text())
        except (OSError, ValueError):
            _glog_disk = {}
    now = dt.datetime.now(dt.timezone.utc).timestamp()
    ent = _glog_disk.get(pid)
    if ent and now - ent.get("ts", 0) < _GLOG_TTL:
        _glog_mem[pid] = ent["log"]
        return ent["log"]
    try:
        import wnba_wowy as W                       # lazy: keeps dashboard import light + numpy-free
        log = W.game_log(pid)
    except Exception:
        log = ent["log"] if ent else []
    _glog_disk[pid] = {"ts": now, "log": log}
    _glog_mem[pid] = log
    try:
        _GLOG_FILE.write_text(json.dumps(_glog_disk))
    except OSError:
        pass
    return log


def _fresh_bars(r):
    """Recompute the same-injury-context bars live: the player's games where tonight's ENTIRE out-set
    was absent, newest-first (up to 10). Returns None to fall back to the stored snapshot (unknown id,
    no logs, or <2 same-context games — the same floor the logger uses)."""
    try:
        pid = NAME2ID.get(r["player"])
        key = STATKEY.get(r["stat"])
        if not pid or not key:
            return None
        blog = [g for g in _glog(pid) if (g.get("min") or 0) > 0]
        out_sets = []
        for nm in (r.get("out_player") or "").split(","):
            opid = NAME2ID.get(nm.strip())
            if opid:
                out_sets.append({g["date"][:10] for g in _glog(opid) if (g.get("min") or 0) > 0})
        if not out_sets:
            return None
        same = [g for g in blog if all(g["date"][:10] not in s for s in out_sets)]
        if len(same) < 2:
            return None
        recent = sorted(same, key=lambda g: g["date"], reverse=True)[:10]
        return [[round(g.get(key, 0)), g.get("matchup", ""), round(g.get("min", 0))] for g in recent]
    except Exception:
        return None


def _samples(r):
    """Bar samples for a row — recomputed live when possible, else the stored snapshot. Cached on the
    row so _bars and _raw_record agree and don't double-fetch."""
    if "_barcache" not in r:
        s = _fresh_bars(r)
        if s is None:
            try:
                s = json.loads(r["samples"]) if r["samples"] else []
            except (ValueError, TypeError):
                s = []
        r["_barcache"] = s
    return r["_barcache"]


def _am(dec):
    dec = float(dec)
    return f"+{round((dec-1)*100)}" if dec >= 2 else f"{round(-100/(dec-1))}"


def _short(n):
    p = (n or "").split()
    return f"{p[0][0]}. {p[-1]}" if len(p) >= 2 else (n or "")


def _conf(r):
    """Confidence = how reliably the projection clears the line: hit rate shrunk toward 50%
    by sample size (odds-INDEPENDENT — price is value, not confidence)."""
    ph, n = r["proj_hit"], r["n_elev"]
    if ph is None or not n:
        return 0.0
    return (ph * n + 0.5 * 6) / (n + 6)


def _units(dec):
    """Recommended stake by ODDS (risk control), NOT model edge — calibrated to the user's own
    ladder staking: full 1u at the anchor (~-110 through +100), then decay hard up the ladder so
    you never overexpose on one player. ~0.5u @ +170, 0.4u @ +200, 0.25u @ +250, 0.2u @ +300,
    0.15u floor for the deep +500/+600 lottery rungs."""
    dec = float(dec)
    if dec <= 2.05:                             # -inf .. ~+105 (favorites through pick'em): base
        return 1.0
    return max(0.15, round((2.0 / dec) ** 2.4 / 0.05) * 0.05)


def _tip_times():
    """{team_abbr: tip_datetime_utc} for today's slate from ESPN, so cards can be ordered
    by game time and show it."""
    et = dt.datetime.now(dt.timezone.utc).astimezone(dt.timezone(dt.timedelta(hours=-4))).strftime("%Y%m%d")
    try:
        j = requests.get(
            f"https://site.api.espn.com/apis/site/v2/sports/basketball/wnba/scoreboard?dates={et}",
            headers={"User-Agent": "Mozilla/5.0"}, timeout=15).json()
    except requests.RequestException:
        return {}
    out = {}
    for e in j.get("events", []):
        try:
            tip = dt.datetime.fromisoformat((e.get("date") or "").replace("Z", "+00:00"))
        except ValueError:
            continue
        for c in e.get("competitions", [{}])[0].get("competitors", []):
            ab = c.get("team", {}).get("abbreviation")
            if ab:
                out[ab] = tip
    return out


def _load(mt_date):
    if not LEDGER.exists():
        return [], (0, 0, 0.0, 0)
    con = sqlite3.connect(LEDGER)
    con.row_factory = sqlite3.Row
    # BOARD shows every un-settled bet from today ONWARD — a next-day play appears the moment
    # it's written (not when its calendar date arrives); a bet drops off the moment it grades
    # (its result then lives in the Tracker record, below).
    rows = [dict(r) for r in con.execute(
        "SELECT * FROM predictions WHERE pred_date>=? AND result IS NULL "
        "ORDER BY pred_date ASC, ev DESC",
        (mt_date,))]
    g = con.execute("SELECT result,odds,side FROM predictions WHERE graded=1 "
                    "AND pred_date>='2026-07-09'").fetchall()
    con.close()
    # durable user-played marks (wnba_played.txt) — read-only, so the ✓ shows on the board
    # independent of when CI last synced the DB column
    pf = HERE / "wnba_played.txt"
    if pf.exists():
        marks = [ln.split("|") for ln in pf.read_text().splitlines() if ln.count("|") == 3]
        for r in rows:
            if any(d == r["pred_date"] and s == r["stat"] and pl.lower() in (r["player"] or "").lower()
                   and abs((r["line"] or 0) - float(ln)) < 1e-9 for d, pl, s, ln in marks):
                r["played"] = 1
    dec = [r for r in g if r[0] in ("over", "under")]
    w = sum(1 for r in dec if r[0] == (r[2] or "over"))   # win = result matches the side we bet
    # P&L weighted by the recommended (odds-based) stake, so the tracker reflects how the
    # plays are actually sized — a losing +240 longshot costs its 0.35u, not a flat 1u.
    u = sum(_units(r[1]) * (r[1] - 1) if r[0] == (r[2] or "over") else -_units(r[1]) for r in dec)
    return rows, (w, len(dec) - w, u, len(rows))


def _raw_record(r):
    """Hit count on the ACTUAL game values shown in the chart — NOT the minutes-honest scaled
    proj_hit. This is what really happened, so the reasoning, the record, and the bars all agree
    on one number. Also returns how many of the last 3 (most recent) went OVER, to surface a
    role that's climbing faster than the flat average shows."""
    s = _samples(r)
    if not s:
        return None
    line = float(r["line"])
    side = (r.get("side") if hasattr(r, "get") else r["side"]) or "over"
    on = (lambda v: v > line) if side == "over" else (lambda v: v < line)
    hits = sum(1 for x in s if on(x[0]))
    recent_over = sum(1 for x in s[:3] if x[0] > line)      # samples are stored newest-first
    return hits, len(s), side, recent_over


def _reasoning(r):
    """A generated, model-grounded 'why the model likes this' line for the dropdown, built from
    the logged features (projection, role change, hit record, stale line, lineup status)."""
    side = (r.get("side") if hasattr(r, "get") else r["side"]) or "over"
    stat = STAT.get(r["stat"], r["stat"])
    line = float(r["line"])
    proj = r["elev_avg"]
    # VOLUME-confirmed points over: a distinct rationale (project off sticky shot volume, not
    # recent points, which lag on shooting variance — the user's laddering edge).
    try:
        vol = json.loads(r["vol"]) if r.get("vol") else {}
    except (ValueError, TypeError):
        vol = {}
    if r.get("basis") == "volume" and vol:
        return (f"<b>Volume play.</b> Projecting <b>{vol['vp']:g} pts</b> off shot VOLUME, not recent "
                f"scoring — her FGA jumped <b>{vol['bf']:g}→{vol['rf']:g}</b> in the elevated role, and "
                f"volume is sticky while shooting is variance. At her {vol['pps']:g} pts-per-shot that's "
                f"a sustainable {vol['vp']:g}, so a cold night can hide it but the <b>over is the value</b> "
                f"— ladder the alt lines the book anchored low.")
    savg, ph, n = r.get("season_avg"), r.get("proj_hit"), r.get("n_elev")
    pm, dmin, drv = r.get("proj_min"), r.get("d_min"), r.get("driver")
    _on = [_short(nm.strip()) for nm in (r.get("out_player") or "").split(",") if nm.strip()]
    out = " + ".join(_on) if _on else None      # full out-set, not a mangled single name
    dl = {"points": "usage", "rebounds": "reb", "assists": "ast"}.get(r["stat"], "")
    role = ""
    if out:
        rb = []
        if dmin is not None and abs(dmin) >= 1:
            rb.append(f"{dmin:+.0f} min")
        if drv is not None and drv >= 1:
            rb.append(f"+{drv:.0f} {dl}")
        role = f"{out} out" + (f" ({', '.join(rb)})" if rb else "")
    b = [f"Model projects <b>{proj:g} {stat}</b>."]
    if side == "under":
        b.append(f"Under the {line:g} line — " + (
            f"{role} lifts the role, but scaled honestly to a ~{pm:.0f}-min night the number lands "
            f"at {proj:g} and the line runs ahead of it." if role
            else f"the projected role doesn't reach {line:g}."))
    else:
        b.append(f"Clears the {line:g} line" + (f" — {role} inherits the vacated role." if role else "."))
    rec = _raw_record(r)
    if rec:
        h, tot, sd, ro = rec
        ctxg = f"games without {out}" if out else "comparable role games"
        b.append(f"In {tot} {ctxg} she finished {sd} {line:g} <b>{h}/{tot}</b> ({h/tot*100:.0f}%).")
        if sd == "under" and ro >= 2:
            b.append(f"⚠ But she's gone OVER in {ro} of her last 3 — the role may be climbing "
                     f"faster than the flat average shows, so treat this under with caution.")
    if r.get("stale") and savg is not None:
        b.append(f"Book anchored near the season avg ({savg:g}) — it hasn't repriced the role.")
    if r.get("confidence") == "bench":
        b.append("⚠ not in the projected starting five — minutes uncertain.")
    return " ".join(b)


def _regime_html(r):
    """Same-lineup comps block: the historical games that best reproduce tonight's FULL impact
    configuration — the ruled-out players absent AND the key teammates present — with the player's
    line in them and whether their average supports the bet. Conditioning on who's IN (not just who's
    out) is the point: usage is set by the whole lineup. A decision aid, not a projection change."""
    try:
        rg = json.loads(r["regime"]) if r.get("regime") else {}
    except (ValueError, TypeError):
        rg = {}
    if not rg or not rg.get("comps"):
        return ""
    side = (r.get("side") if hasattr(r, "get") else r["side"]) or "over"
    line = float(r["line"])
    stat = STAT.get(r["stat"], r["stat"])
    avg = rg["comp_avg"]
    names = ", ".join(rg.get("sig_names", [])[:3]) or "key players"
    # the IN-config that defines a TRUE comp — who's on the floor caps usage as much as who's out
    # (Johannes avg 13.7 ignoring this, but 9.5 once Ionescu/Stewart must be present as they are
    # tonight). Show it so the comp is legible: same lineup, not just same absences.
    inn = ", ".join(n.split()[-1] for n in rg.get("in_names", [])[:3])
    incfg = f' · <b>{html.escape(inn)}</b> in' if inn else ""
    np = rg.get("n_primary", rg.get("n_comps", 0))
    supports = (avg < line) if side == "under" else (avg > line)
    verdict = "supports the " + side if supports else "⚠ leans against the " + side
    vcls = "sup" if supports else "warn"
    # mark the chips that match tonight's lineup BEST (the ones the avg is over) so it's obvious
    # which games are true same-lineup comps vs looser ones (a blowout where a starter also sat).
    bestm = max((c.get("match", 0) for c in rg["comps"]), default=0)
    chips = "".join(f'<span class="cmp{" pr" if c.get("match", 0) >= bestm - 0.08 else ""}">'
                    f'{html.escape(c["date"][5:])} '
                    f'{html.escape(str(c["opp"]))} <b>{c["val"]:g}</b> · {c["min"]:g}\'</span>'
                    for c in rg["comps"])
    div = ' · <span class="warn">tonight differs from her recent games</span>' if rg.get("divergent") else ""
    return (f'<div class="regime"><div class="rgh">Same-lineup comps · <b>{html.escape(names)}</b> out'
            f'{incfg} — avg <b>{avg:g}</b> {stat} over {np} (<span class="{vcls}">{verdict}</span>){div}</div>'
            f'<div class="cmps">{chips}</div></div>')


def _bars(r):
    """Dropdown: generated reasoning + a PropsCash-style game log. Each game's ACTUAL stat is a
    bar (green if it cashed our side, red if not) with the line drawn across, and a gray MINUTES
    bar behind it (own 0-40 scale) so the role context is visible. Opponent under each bar."""
    why = f'<div class="why">{_reasoning(r)}</div>{_regime_html(r)}'
    s = _samples(r)
    if not s:
        return f'<div class="bars">{why}<div class="nodata">no game data</div></div>'
    s = list(reversed(s))                              # newest-first -> show oldest-left
    line = float(r["line"])
    side = (r.get("side") if hasattr(r, "get") else r["side"]) or "over"
    vals = [x[0] for x in s]
    # TWO scales so the gray MINUTES bar is always clearly TALLER than the colored stat bar
    # (props.cash style): minutes fill toward the top on their own 0-42 range (a 30-min night ≈
    # 71%), stats are compressed into the lower ~62% so the minute number atop every bar stays
    # readable and never collides with the stat value.
    mx = max(max(vals), line) * 1.62 or 1
    onside = (lambda v: v > line) if side == "over" else (lambda v: v < line)
    hits = sum(1 for v in vals if onside(v))
    # the bars are the player's games matching tonight's injury context (out-set absent), so name it
    outs = ", ".join(_short(nm.strip()) for nm in (r.get("out_player") or "").split(",") if nm.strip())
    note = ("volume-confirmed role · bars = actual pts (shooting varies, volume doesn't)"
            if r["basis"] == "volume" else (f"games without {outs}" if outs else "elevated-role games")
            if r["basis"] == "elevated" else f"projected to ~{r['proj_min']:.0f} min")
    cols = ""
    for x in s:
        v = x[0]
        mn = x[2] if len(x) > 2 else 0                  # minutes that game (overlay, own 0-40 scale)
        cols += (f'<div class="col">'
                 f'<div class="m" style="height:{min(mn/42*100, 97):.0f}%"><span class="mv">{mn:g}\'</span></div>'
                 f'<div class="b {"o" if onside(v) else "u"}" style="height:{v/mx*100:.1f}%">'
                 f'<span class="bv">{v:g}</span></div></div>')
    opps = "".join(f'<span>{html.escape(str(o) or "")}</span>' for _, o, *_ in s)
    return (f'<div class="bars">{why}<div class="chart">'
            f'<div class="pline" style="bottom:{line/mx*100:.1f}%"><span>{line:g}</span></div>'
            f'{cols}</div><div class="opps">{opps}</div>'
            f'<div class="bnote">{hits}/{len(s)} {side} {line:g} · gray bar = minutes · {note}</div></div>')


def _splits(r):
    """The player's OVER/UNDER hit rate AT THIS LINE over recent windows — L5 / L10 / season / vs
    this opponent (H2H) — from the live game log. Returns {'l5':(hits,n), ...} or None. This is the
    props.cash time-split heatmap: raw recent form at the exact number, beside our ROLE edge."""
    pid = NAME2ID.get(r["player"])
    key = STATKEY.get(r["stat"])
    if not pid or not key:
        return None
    log = [g for g in _glog(pid) if (g.get("min") or 0) > 0]      # played games, newest-first
    if not log:
        return None
    line = float(r["line"])
    side = (r.get("side") if hasattr(r, "get") else r["side"]) or "over"

    def hr(games):
        vals = [g.get(key) for g in games if g.get(key) is not None]
        if not vals:
            return None
        return sum(1 for v in vals if (v > line) == (side == "over")), len(vals)

    opp = (r.get("opp") or "").upper()
    h2h = hr([g for g in log if (g.get("matchup") or "").upper() == opp]) if opp else None
    return {"l5": hr(log[:5]), "l10": hr(log[:10]), "szn": hr(log), "h2h": h2h}


def _hrcell(lbl, hr, role=False):
    """One heatmap cell: hit% at the line, W/N underneath. The TINT lives on the cell (faint green/
    red wash, desaturated value) — not glowing text — so the grid reads as a heatmap, and saturated
    green stays reserved for the model edge. `role` marks our injury-context cell (blue label)."""
    base = "gc r" if role else "gc"
    if not hr or not hr[1]:
        return (f'<div class="{base}"><span class="gcl">{lbl}</span>'
                f'<span class="gcv dim">—</span><span class="gcs">&nbsp;</span></div>')
    pct = hr[0] / hr[1] * 100
    cls = " hot" if pct >= 65 else (" cold" if pct <= 35 else "")   # hot/cold: no collision with .b bars
    return (f'<div class="{base}{cls}"><span class="gcl">{lbl}</span>'
            f'<span class="gcv">{pct:.0f}%</span><span class="gcs">{hr[0]}/{hr[1]}</span></div>')


def _book_prices(r):
    """[(book, dec_odds)] for THIS prop's bet side, BEST price first, from the last day of fd_lines
    (FanDuel + DraftKings live in the same table). Reads the freshest lines DB (resilient to a
    dropped collect-odds cron). Lets the card show WHERE the best number is. [] if unreachable."""
    import wnba_props_db as PDB
    db = PDB.props_db()
    if not Path(db).exists():
        return []
    side = (r.get("side") if hasattr(r, "get") else r["side"]) or "over"
    try:
        con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
        rows = con.execute(
            "SELECT COALESCE(book,'fd') b, odds, collected_at FROM fd_lines WHERE sport='wnba' "
            "AND player=? AND stat=? AND ROUND(line,1)=? AND side=? "
            "AND collected_at > datetime('now','-1 day')",
            (r["player"], r["stat"], round(float(r["line"]), 1), side)).fetchall()
        con.close()
    except Exception:
        return []
    if not rows:
        return []
    # CURRENT snapshot only: the LATEST quote per book, and drop a book whose newest quote for this
    # rung is stale (>FRESH_MIN behind the newest) — never MAX-over-time, which showed an old, more
    # generous price as the live 'best price' (the same bug fixed in posted_props).
    newest = max(ca for _, _, ca in rows)
    try:
        cutoff = (dt.datetime.fromisoformat(newest) - dt.timedelta(minutes=FRESH_MIN)).isoformat()
    except ValueError:
        cutoff = ""
    latest = {}                                        # book -> (collected_at, odds)
    for b, o, ca in rows:
        if o is None or ca < cutoff:
            continue
        if b not in latest or ca > latest[b][0]:
            latest[b] = (ca, o)
    return sorted([(b, o) for b, (ca, o) in latest.items()], key=lambda x: -x[1])


def _prop_row(r, rungs=None):
    """props.cash-style prop: side pill + line + stat, best-book odds + model edge on the right, the
    hit-rate HEATMAP (ROLE injury-context · L5 · L10 · season · H2H, green/red), and a compact
    context line (usage driver + matchup D + the runner-up book price). Taps to expand the bars."""
    stat = STAT.get(r["stat"], r["stat"].upper())
    side = (r.get("side") if hasattr(r, "get") else r["side"]) or "over"
    o = "O" if side == "over" else "U"
    ev = r.get("ev")
    edge_v = f"{ev*100:+.0f}%" if ev is not None else ""
    ecls = "hi" if (ev or 0) >= 0.15 else ("mid" if (ev or 0) >= 0.07 else "lo")
    # ROLE cell = the injury-context record (our edge); a volume play shows the volume probability
    if r.get("basis") == "volume" and r.get("proj_hit"):
        ph = r["proj_hit"]
        role_cell = (f'<div class="gc r{" hot" if ph >= 0.6 else ""}"><span class="gcl">ROLE</span>'
                     f'<span class="gcv">{ph*100:.0f}%</span><span class="gcs">vol</span></div>')
    else:
        rec = _raw_record(r)
        role_cell = _hrcell("ROLE", (rec[0], rec[1]) if rec else None, role=True)
    sp = _splits(r) or {}
    grid = (role_cell + _hrcell("L5", sp.get("l5")) + _hrcell("L10", sp.get("l10"))
            + _hrcell("SZN", sp.get("szn")) + _hrcell("H2H", sp.get("h2h")))
    # context line — our injury driver + the DvP matchup note (qualitative signals, not hit rates)
    ctx, drv, dm = [], r.get("driver"), r.get("d_min")
    dlbl = {"points": "usg", "rebounds": "reb", "assists": "ast"}.get(r["stat"], "usg")
    if drv is not None and drv >= 1:
        ctx.append(f'<span class="cdrv">▲{drv:+.0f} {dlbl}</span>')
    elif dm is not None and dm > 2:
        ctx.append(f'<span class="cdrv">▲{dm:+.0f} min</span>')
    try:
        import wnba_dvp as DVP
        note = DVP.matchup_note((r.get("opp") or "").upper(), r.get("pos") or "", r["stat"])
        if note:
            ctx.append(f'<span class="cdvp {note}">{note} D</span>')
    except Exception:
        pass
    if r.get("elev_avg") is not None:
        ctx.append(f'proj {r["elev_avg"]:g}')
    # BEST PRICE across books — show WHICH book has the best number, runner-up in the context line
    bp = _book_prices(r)
    if bp:
        best_bk, best_dec = bp[0]
        odds_html = f'<span class="podds">{_am(best_dec)}</span><span class="pbk">{best_bk.upper()}</span>'
        if len(bp) > 1:
            ctx.append(f'{bp[1][0].upper()} {_am(bp[1][1])}')
    else:
        best_dec = float(r["odds"])
        odds_html = f'<span class="podds">{_am(best_dec)}</span>'
    ctxline = f'<div class="pctx">{" · ".join(ctx)}</div>' if ctx else ""
    juice = ' <span class="juice">juice</span>' if best_dec < 1.80 else ""
    played = ' <span class="pv">✓</span>' if r.get("played") else ""
    # GROUP same-stat/same-side rungs (an under whose anchor line moved across scans, or an overs
    # ladder): ONE card showing the line RANGE + a strip of every rung's line@odds — declutters
    # without dropping any flag (each rung stays its own ledger row / placed bet).
    if rungs and len(rungs) > 1:
        lns = sorted(x["line"] for x in rungs)
        line_disp = f"{lns[0]:g}–{lns[-1]:g}"
        chips = []
        for rr in sorted(rungs, key=lambda x: x["line"]):
            bpr = _book_prices(rr)
            chips.append(f'<span class="rung"><b>{rr["line"]:g}</b> '
                         f'<span class="ro">{_am(bpr[0][1] if bpr else float(rr["odds"]))}</span></span>')
        rungs_html = f'<div class="prungs"><span class="rlbl">rungs</span>{"".join(chips)}</div>'
    else:
        line_disp, rungs_html = f"{r['line']:g}", ""
    return f"""
      <div class="prop" data-side="{side}" onclick="this.nextElementSibling.classList.toggle('open')">
        <div class="prow">
          <span class="pind {o.lower()}">{o}</span>
          <span class="plno">{line_disp}</span><span class="pstat">{stat}</span>
          <span class="psp"></span>
          {odds_html}{juice}
          <span class="pedge {ecls}">{edge_v}</span>{played}<span class="pchev">›</span></div>
        <div class="pgrid">{grid}</div>{ctxline}{rungs_html}
      </div>{_bars(r)}"""


def _player_block(player, rows):
    """One beneficiary inside a game: team logo + name, lineup status as a quiet dot-chip, projected
    minutes right-aligned. The team-level injury context (who's out) lives on the GAME header, not
    here. Color discipline: the status is a small colored DOT + gray text, not colored text — the
    saturated green on this surface belongs to the edge number alone."""
    r0 = rows[0]
    team = (r0.get("team") or "").upper()
    logo = (f'<img class="plogo" src="{LOGO.format(team.lower())}" alt="" loading="lazy" '
            f'onerror="this.style.display=\'none\'">' if team else "")
    cb = {"confirmed": ("starting", "ok"), "bench": ("bench", "warn"),
          "likely": ("likely", "mid"), "projected": ("TBD", "mid")}.get(
              r0.get("confidence") or "projected", ("", ""))
    flag = f'<span class="pflag"><i class="sdot {cb[1]}"></i>{cb[0]}</span>' if cb[0] else ""
    pm, dm = r0.get("proj_min"), r0.get("d_min")
    mins = ""
    if pm:
        trend = f" ▲{dm:+.0f}" if dm is not None else ""
        mins = f'<span class="pmin">~{pm:.0f}\'{trend}</span>'
    sp = r0.get("spread")
    dogchip = (f'<span class="dog">+{sp:.0f} dog</span>' if sp is not None and sp >= 8 else "")
    # group same-stat/same-side rungs into ONE card (the anchor line can move across scans and the
    # keep-every-flag rule preserves each rung — so show them as one play with its line range, no flag
    # dropped). Order groups by best rung EV; a single-rung group renders exactly as before.
    groups = {}
    for r in rows:
        groups.setdefault((r["stat"], (r.get("side") or "over")), []).append(r)
    ordered = sorted(groups.values(), key=lambda g: -max((x.get("ev") or 0) for x in g))
    props = "".join(_prop_row(sorted(g, key=lambda x: -(x.get("ev") or 0))[0],
                              rungs=g if len(g) > 1 else None) for g in ordered)
    return (f'<div class="pblk">'
            f'<div class="phd">{logo}<span class="pname">{html.escape(_short(player))}</span>'
            f'{flag}{dogchip}<span class="psp2"></span>{mins}</div>{props}</div>')


def _game_group(players, tips, today=None):
    """A GAME: a header (matchup + tip time / slate day) and the shared injury context (who's
    out), then the beneficiary blocks. `players` = [(player, rows)] already ordered by edge. A
    play whose slate date isn't today is labelled with its weekday+date (tips only covers today)."""
    r0 = players[0][1][0]
    team = (r0.get("team") or "").upper()
    opp = (r0.get("opp") or "").upper()
    tip = tips.get(team)
    tiptime = tip.astimezone(MT).strftime("%-I:%M %p") if tip else ""
    pd = r0.get("pred_date")
    if pd and today and pd != today:                       # a next-day play: label the slate day
        try:
            when = dt.date.fromisoformat(pd).strftime("%a %-m/%-d") + (f" · {tiptime}" if tiptime else "")
        except ValueError:
            when = pd
    else:
        when = tiptime
    outset = {_short(nm.strip()) for _, prs in players for r in prs
              for nm in (r.get("out_player") or "").split(",") if nm.strip()}
    outs = " + ".join(sorted(outset))
    blocks = "".join(_player_block(p, prs) for p, prs in players)
    gedge = max((x.get("ev") or 0) for _, prs in players for x in prs)
    gtip = tip.timestamp() if tip else 9e15

    def glogo(ab):
        return (f'<img class="glogo" src="{LOGO.format(ab.lower())}" alt="" loading="lazy" '
                f'onerror="this.style.display=\'none\'">' if ab else "")
    return (f'<div class="game" data-edge="{gedge:.4f}" data-tip="{gtip:.0f}">'
            f'<div class="ghd"><span class="gmatch">{glogo(team)}{team}'
            f'<span class="gvs">vs</span>{glogo(opp)}{opp or "—"}</span>'
            f'<span class="gtime">{when}</span></div>'
            + (f'<div class="gout"><i class="sdot warn"></i>{html.escape(outs)} out</div>' if outs else "")
            + blocks + "</div>")


def _load_tt():
    f = HERE / "tt_board.json"
    if not f.exists():
        return None
    try:
        return json.loads(f.read_text())
    except (ValueError, OSError):
        return None


def _tracker_panel(wnba_rec, tt_json):
    """Tracker tab — live record / hit rate / units for WNBA and Table Tennis, flat 1u,
    updated as each event settles."""
    def card(emoji, title, w, l, u, note):
        n = w + l
        hit = f"{w/n*100:.0f}%" if n else "—"
        roi = f"{u/n*100:+.0f}%" if n else ""
        ucls = "up" if u > 0 else ("down" if u < 0 else "")
        return f"""
      <div class="tcard">
        <div class="thead">{emoji} {html.escape(title)}</div>
        <div class="trow">
          <div class="tbox"><div class="tk">Record</div><div class="tv">{w}-{l}</div></div>
          <div class="tbox"><div class="tk">Hit rate</div><div class="tv">{hit}</div></div>
          <div class="tbox"><div class="tk">Units</div><div class="tv {ucls}">{u:+.1f}u</div></div>
        </div>
        <div class="tsub">{html.escape(note)}{(' · ROI ' + roi) if roi else ''}</div>
      </div>"""
    w, l, u = wnba_rec
    out = card("🏀", "WNBA injury props", w, l, u, "staked by odds (ladder) · settles live · since 7/9")
    tt = (tt_json or {}).get("tracker")
    if tt:
        out += card("🏓", "Table tennis", tt.get("w", 0), tt.get("l", 0), tt.get("u", 0.0),
                    "flat 1u · settles live · since 7/9")
    else:
        out += ('<div class="tcard"><div class="thead">🏓 Table tennis</div>'
                '<div class="tsub">connecting… (needs the tt-elite bridge)</div></div>')
    # INJURY-TIMING CLV — the real proof-of-edge: does the line move toward our read from the moment
    # we flag the injury (open) to the close? Accumulates as slates settle; the verdict is the green
    # light to scale real money.
    try:
        import wnba_clv as CLV
        cv = CLV.verdict()
    except Exception:
        cv = None
    if cv and not cv["ready"]:
        out += (f'<div class="tcard"><div class="thead">🎯 Injury-timing CLV</div>'
                f'<div class="tsub">Accumulating <b>{cv["n"]}/{cv["need"]}</b> shadows over '
                f'<b>{cv.get("dates", 0)}/{cv.get("need_dates", 5)}</b> slates — one night\'s shadows are '
                f'correlated, so the "are we beating the close?" verdict waits for breadth. This is the '
                f'proof the timing edge is real before scaling stakes.</div></div>')
    elif cv:
        lm, pos = cv["line_move"], cv["pos_rate"]
        good = lm > 0 and pos >= 0.5
        mixed = lm > 0 and pos < 0.5
        vcls = "up" if good else ("" if mixed else "down")
        vtext = ('✓ line moves toward our read — beating the close' if good
                 else '~ mixed: mean move positive but most lines drift against'
                 if mixed else '✗ line drifts against us')
        hit = f' · realized {cv["hit"] * 100:.0f}%' if cv["hit"] is not None else ""
        out += f"""
      <div class="tcard">
        <div class="thead">🎯 Injury-timing CLV</div>
        <div class="trow">
          <div class="tbox"><div class="tk">Line move</div><div class="tv {vcls}">{lm:+.2f}</div></div>
          <div class="tbox"><div class="tk">Positive</div><div class="tv">{pos * 100:.0f}%</div></div>
          <div class="tbox"><div class="tk">Corr</div><div class="tv">{cv["corr"]:+.2f}</div></div>
        </div>
        <div class="tsub">{vtext}{hit} · {cv['n']} shadows / {cv.get('dates', '?')} slates (open vs close)</div>
      </div>"""
    return out


def _tt_ladder(lad, play_to, zone):
    """Tap-to-expand hit-rate ladder: the raw H2H hit rate of the FLAGGED SIDE at every line
    a book might post (70.5–80.5), so the user reads the rate at THEIR exact line. Over bet
    -> over% per line; under bet -> under% per line. The ◄ marks the furthest line still
    worth playing (the model's validated cutoff); rows PAST that edge are dimmed = skip."""
    if not lad:
        return '<div class="ttlad"><div class="ladnote">no H2H line ladder</div></div>'
    over_side = zone.startswith("O")
    sidelbl = "over" if over_side else "under"
    rows = ""
    for r in lad:
        pct = r["op"] if over_side else 100 - r["op"]
        hit = r["o"] if over_side else r["u"]
        miss = r["u"] if over_side else r["o"]
        edge = abs(r["line"] - play_to) < 0.01
        noplay = (r["line"] > play_to) if over_side else (r["line"] < play_to)
        cls = " mark" if edge else (" dim" if noplay else "")
        lbl = f'{r["line"]:g}' + (' <span class="ladm">◄</span>' if edge else "")
        od = f'{r["od"]:.2f}' if r.get("od") else '·'    # actual bmbets soft price at this line
        rows += (f'<div class="ladrow{cls}">'
                 f'<span class="ladl">{lbl}</span>'
                 f'<span class="ladbar"><i style="width:{pct}%"></i></span>'
                 f'<span class="ladv">{pct}%</span>'
                 f'<span class="ladr">{hit}-{miss}</span>'
                 f'<span class="ladod">{od}</span></div>')
    return (f'<div class="ttlad">'
            f'<div class="ladhead"><span>Line</span><span>{sidelbl} hit rate</span>'
            f'<span class="ladv">%</span><span class="ladr">rec</span><span class="ladod">odds</span></div>'
            f'{rows}'
            f'<div class="ladnote">◄ play {sidelbl} up to here · odds = softest book price · dimmed = skip</div></div>')


def _tt_panel(data):
    """Table Tennis tab — today's flagged bets, grouped by league, ordered by game time.
    Each matchup taps open to a per-line hit-rate ladder."""
    if not data:
        return ('<div class="empty">Table tennis feed connecting…<br>'
                '<span>Once the tt-elite bridge is set up, today\'s TT bets show here.</span></div>')
    bets = data.get("bets", [])
    if not bets:
        return ('<div class="empty">No TT bets flagged right now.<br>'
                '<span>Fixtures post a few hours before play — check back closer to the slate.</span></div>')
    default_line = data.get("model_line", 74.5)
    by = defaultdict(list)
    for b in bets:
        by[b["league"]].append(b)
    out = []
    for league in sorted(by):
        games = sorted(by[league], key=lambda b: b.get("ts") or 0)
        cards = ""
        for b in games:
            when = (dt.datetime.fromtimestamp(b["ts"], MT).strftime("%-I:%M %p")
                    if b.get("ts") else "TBD")
            side = html.escape(b.get("side", ""))
            book = b.get("book")     # actual bmbets main line + softest price (None until odds land)
            bk = (f' · <span class="ttbook">book {"O" if b.get("side", "").startswith("O") else "U"}'
                  f'{book["line"]:g} @{book["od"]:.2f}</span>') if book else ""
            lad = _tt_ladder(b.get("ladder", []), b.get("play_to", default_line), b.get("side", ""))
            cards += f"""
      <div class="ttrow" onclick="this.nextElementSibling.classList.toggle('open')">
        <div class="ttmain"><b>{html.escape(b['p1'])}</b> v {html.escape(b['p2'])}<span class="ttchev">›</span></div>
        <div class="ttsub">{when} MT · <span class="ttside">{side}</span> · {b['rec']} ({b['raw']}%) · {b['u']:g}u{bk}</div>
      </div>{lad}"""
        out.append(f'<div class="card"><h3 class="ttlg">{html.escape(league)}</h3>{cards}</div>')
    return "\n".join(out)


_WL_STAT = {"points": "pts", "rebounds": "reb", "assists": "ast", "pra": "PRA",
            "pts_reb": "P+R", "pts_ast": "P+A", "reb_ast": "R+A"}


def _watchlist_html():
    """Questionable-tier watchlist: provisional spots that open up IF a game-time-decision star
    sits. Rendered distinctly (amber, dashed) so it never reads as a firm bet. Read from the JSON
    wnba_alert writes each cycle; missing / stale (not today) / empty -> no section."""
    f = HERE / "wnba_watchlist.json"
    if not f.exists():
        return ""
    try:
        d = json.loads(f.read_text())
    except (ValueError, OSError):
        return ""
    today = dt.datetime.now(ET).date().isoformat()   # match the ET slate date the writer stamps
    spots = d.get("spots") or []
    if d.get("date") != today or not spots:
        return ""
    by_star = defaultdict(list)
    for s in sorted(spots, key=lambda s: -(s.get("ev") or 0)):
        by_star[(s.get("star"), s.get("status"), s.get("sit"), s.get("lead"))].append(s)
    blocks = []
    for (star, status, sit, lead), ss in by_star.items():
        sitpct = f"~{sit * 100:.0f}% to sit" if sit is not None else ""
        # lead time is the tell: a late-breaking Q usually sits (and is the widest timing edge)
        ltag = (f" · {'⚠ ' if lead < 6 else ''}tagged {lead:.0f}h pre-tip" if lead is not None else "")
        legs = "".join(
            f'<div class="wl-leg"><b>{html.escape(_short(s["player"]))}</b> '
            f'{_WL_STAT.get(s.get("stat"), s.get("stat"))} o{s["line"]:g}'
            f'<span class="wl-ev">+{(s.get("ev") or 0) * 100:.0f}%</span>'
            f'<span class="wl-meta">proj {s.get("elev_avg", 0):g} · '
            f'{round((s.get("hit") or 0) * (s.get("n") or 0))}/{s.get("n") or 0} in role</span></div>'
            for s in ss)
        blocks.append(
            f'<div class="wl-grp"><div class="wl-hd">if <b>{html.escape(star or "?")}</b> '
            f'({html.escape(status or "Q")} · {sitpct}{ltag}) sits</div>{legs}</div>')
    return ('<div class="watchlist"><div class="wl-title">⏳ Watchlist · questionable stars '
            '<span>— provisional, not firm bets; fire when ruled out</span></div>'
            + "".join(blocks) + "</div>")


def _openers_html():
    """⚡ Openers: beatable opening lines just posted — line-shopping heads-ups (bet the soft number
    before the book moves). DISTINCT from the tracked-bet cards above: these are NOT flagged injury
    bets and they don't hit the record. Recomputed each ~60s poll by wnba_watch -> wnba_openers.json;
    stale / other-day / empty -> no section."""
    f = HERE / "wnba_openers.json"
    if not f.exists():
        return ""
    try:
        d = json.loads(f.read_text())
    except (ValueError, OSError):
        return ""
    today = dt.datetime.now(ET).date().isoformat()
    spots = d.get("spots") or []
    if d.get("date") != today or not spots:
        return ""
    legs = "".join(f'<div class="op-leg">{html.escape(s.get("msg", ""))}</div>' for s in spots[:12])
    return ('<div class="openers"><div class="op-title">⚡ Openers'
            '<span> · beatable lines just posted · line-shopping, not tracked bets</span></div>'
            f'{legs}</div>')


def build():
    now = dt.datetime.now(dt.timezone.utc).astimezone(MT)   # MT for the displayed clock only
    # the BOARD's slate day is ET (matches pred_date the scanner stamps) — using MT hid plays during
    # the ET-night / MT-evening window (a bet stamped ET-tomorrow was invisible on the MT-today board).
    today = dt.datetime.now(ET).date().isoformat()        # ET slate date the scanner stamps
    rows, (w, l, u, pend) = _load(today)
    tips = _tip_times()
    # GROUP BY DAY > GAME > player — the board shows tonight's plays AND any already-posted
    # next-day plays (keyed by date so the same matchup on back-to-back days stays separate).
    by_player = defaultdict(list)
    for r in rows:
        by_player[(r.get("pred_date"), r["player"])].append(r)
    games = defaultdict(list)                              # {(date, teams-pair): [(player, rows)]}
    for (pd, player), prs in by_player.items():
        team = (prs[0].get("team") or "").upper()
        opp = (prs[0].get("opp") or "").upper()
        games[(pd, tuple(sorted((team, opp))))].append((player, prs))

    def _pedge(prs):
        return max((r.get("ev") or 0) for r in prs)
    # soonest slate first, then strongest edge within a slate
    order = sorted(games.items(),
                   key=lambda kv: (kv[0][0] or "9999-99-99", -max(_pedge(prs) for _, prs in kv[1])))
    ordered = [pl for _, pl in order]
    for pl in ordered:                                    # strongest player first within each game
        pl.sort(key=lambda pp: -_pedge(pp[1]))
    cards = "\n".join(_game_group(pl, tips, today) for pl in ordered) if ordered else \
        '<div class="empty">No plays flagged yet.<br><span>The watcher checks every ~60s and fills this in the moment a key player is ruled out.</span></div>'
    openers_html = _openers_html()
    wl_html = _watchlist_html()
    tt_json = _load_tt()
    tt_html = _tt_panel(tt_json)
    tracker_html = _tracker_panel((w, l, u), tt_json)
    doc = f"""<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Today's Plays</title>
<style>
  :root {{ color-scheme: dark; }}
  * {{ box-sizing:border-box; -webkit-tap-highlight-color:transparent; }}
  body {{ margin:0; background:#08090c; color:#e8ecf2;
    font:16px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; -webkit-font-smoothing:antialiased; }}
  .wrap {{ max-width:600px; margin:0 auto; padding:22px 16px 48px; }}
  h1 {{ font-size:21px; font-weight:800; margin:0; letter-spacing:-.02em; }}
  .live {{ display:flex; align-items:center; gap:6px; color:#78818f; font-size:12px; margin-top:5px; }}
  .dot {{ width:7px; height:7px; border-radius:50%; background:#22c55e; box-shadow:0 0 0 3px #22c55e22; }}
  .stats {{ display:grid; grid-template-columns:repeat(3,1fr); gap:10px; margin:16px 0 24px; }}
  .stat {{ background:#121620; border:1px solid #1f2836; border-radius:14px; padding:13px 12px; min-height:74px;
    display:flex; flex-direction:column; justify-content:space-between; }}
  .stat .k {{ color:#7d8696; font-size:10.5px; text-transform:uppercase; letter-spacing:.06em; }}
  .stat .v {{ font-size:21px; font-weight:700; line-height:1; }}
  .stat .sv {{ color:#7d8696; font-size:12px; font-weight:500; }}
  h2 {{ font-size:10.5px; color:#5c6572; text-transform:uppercase; letter-spacing:.08em; margin:0 0 10px; font-weight:700; }}
  .fbar {{ display:flex; gap:8px; margin:0 0 20px; flex-wrap:wrap; }}
  .fgrp {{ display:flex; gap:3px; background:#0f1116; border:1px solid #191d26; border-radius:11px; padding:3px; }}
  .pill {{ padding:6px 13px; font-size:12.5px; font-weight:700; color:#78818f; border-radius:8px; cursor:pointer; user-select:none; }}
  .pill.on {{ background:#232c3d; color:#f2f5f9; }}
  /* GAME group — the top of the hierarchy: logos + matchup, hairline rule, generous separation */
  .game {{ margin-bottom:32px; }}
  .ghd {{ display:flex; justify-content:space-between; align-items:center; padding:0 2px 9px;
    margin-bottom:11px; border-bottom:1px solid #14181f; }}
  .gmatch {{ font-size:17px; font-weight:800; letter-spacing:-.01em; display:flex; align-items:center; gap:7px; }}
  .glogo {{ width:20px; height:20px; object-fit:contain; filter:drop-shadow(0 0 1.5px rgba(255,255,255,.3)); }}
  .gvs {{ color:#4d5560; font-weight:600; font-size:11px; margin:0 1px; }}
  .gtime {{ color:#6b7484; font-size:12px; font-weight:600; font-variant-numeric:tabular-nums; }}
  .gout {{ display:flex; align-items:center; gap:6px; color:#c08a4d; font-size:12px; font-weight:600;
    margin:-3px 2px 12px; }}
  .sdot {{ width:6px; height:6px; border-radius:50%; display:inline-block; flex:none; }}
  .sdot.ok {{ background:#37d67f; }} .sdot.warn {{ background:#eaa15a; }} .sdot.mid {{ background:#5b9dff; }}
  /* PLAYER block — logo + name lead; status is a quiet dot-chip; minutes right-aligned meta */
  .pblk {{ background:#0f1116; border:1px solid #191d26; border-radius:14px; padding:15px 16px 9px; margin-bottom:11px; }}
  .phd {{ display:flex; align-items:center; gap:9px; }}
  .plogo {{ width:27px; height:27px; object-fit:contain; filter:drop-shadow(0 0 1.5px rgba(255,255,255,.3)); }}
  .pname {{ font-size:22px; font-weight:800; letter-spacing:-.015em; }}
  .pflag {{ display:flex; align-items:center; gap:5px; color:#8a93a3; font-size:13px; font-weight:600; white-space:nowrap; }}
  .psp2 {{ flex:1; }}
  .pmin {{ color:#78818f; font-size:13.5px; font-weight:600; white-space:nowrap; font-variant-numeric:tabular-nums; }}
  .dog {{ color:#d9985c; font-size:12.5px; font-weight:700; }}
  .watchlist {{ margin-top:24px; padding-top:2px; border-top:1px solid #171c25; }}
  .wl-title {{ color:#eaa15a; font-size:12px; font-weight:800; letter-spacing:.04em; text-transform:uppercase; margin:16px 2px 11px; }}
  .wl-title span {{ color:#7d8696; font-weight:600; text-transform:none; letter-spacing:0; }}
  .openers {{ margin-top:22px; }}
  .op-title {{ color:#5b9dff; font-size:12px; font-weight:800; letter-spacing:.04em; text-transform:uppercase; margin:16px 2px 11px; }}
  .op-title span {{ color:#7d8696; font-weight:600; text-transform:none; letter-spacing:0; }}
  .op-leg {{ background:#0f1116; border:1px solid #191d26; border-radius:11px; padding:11px 13px; margin-bottom:8px; font-size:14px; color:#cdd4de; font-variant-numeric:tabular-nums; }}
  .wl-grp {{ border-left:3px solid #eaa15a; background:#0f1116; border:1px solid #191d26; border-left-width:3px;
    border-radius:10px; padding:10px 13px; margin-bottom:9px; }}
  .wl-hd {{ color:#c9a06a; font-size:12px; font-weight:700; margin-bottom:6px; }}
  .wl-hd b {{ color:#e8ecf2; }}
  .wl-leg {{ font-size:13.5px; padding:3px 0; }}
  .wl-leg b {{ color:#e8ecf2; font-weight:800; }}
  .wl-ev {{ color:#e8ecf2; font-weight:800; margin-left:7px; }}
  .wl-meta {{ color:#7d8696; font-size:11px; margin-left:7px; }}
  /* PROP row — the read order is bet -> price -> EDGE (the one saturated-green number) */
  .prop {{ padding:13px 0 5px; cursor:pointer; border-top:1px solid #14181f; margin-top:9px; }}
  .pblk .prop:first-of-type {{ border-top:0; margin-top:8px; }}
  .prow {{ display:flex; align-items:center; gap:9px; }}
  .pind {{ width:27px; height:27px; border-radius:50%; display:grid; place-items:center;
    font-size:13px; font-weight:800; border:1.5px solid; flex:none; }}
  .pind.o {{ color:#57b389; border-color:#57b38944; }}
  .pind.u {{ color:#6a9fe8; border-color:#6a9fe844; }}
  .plno {{ font-size:24px; font-weight:800; font-variant-numeric:tabular-nums; letter-spacing:-.015em; }}
  .pstat {{ color:#78818f; font-weight:700; font-size:13px; letter-spacing:.04em; }}
  .psp {{ flex:1; }}
  .podds {{ color:#6ba3f5; font-weight:700; font-size:16px; font-variant-numeric:tabular-nums; }}
  .pbk {{ color:#78818f; font-size:9.5px; font-weight:800; letter-spacing:.04em; margin-left:3px;
    background:#161b24; border:1px solid #1d232e; border-radius:4px; padding:1px 4px; position:relative; top:-1px; }}
  .pedge {{ font-weight:800; font-size:20px; font-variant-numeric:tabular-nums; letter-spacing:-.015em; }}
  .pedge.hi {{ color:#37d67f; }} .pedge.mid {{ color:#c3cdda; }} .pedge.lo {{ color:#6b7484; }}
  .pchev {{ color:#3b4452; font-size:20px; transition:transform .15s; }}
  .prop:has(+ .bars.open) .pchev {{ transform:rotate(90deg); }}
  .pv {{ color:#78818f; font-weight:800; font-size:13px; }}
  .juice {{ color:#c08a4d; font-size:10px; font-weight:700; white-space:nowrap; }}
  /* HEATMAP — tint the CELL (faint wash), not the text; values stay near-neutral */
  .pgrid {{ display:grid; grid-template-columns:repeat(5,1fr); gap:5px; margin:10px 0 2px; }}
  .gc {{ background:#0b0d12; border:1px solid #161b24; border-radius:8px; padding:6px 2px 5px;
    display:flex; flex-direction:column; align-items:center; gap:1px; }}
  .gc.hot {{ background:rgba(55,214,127,.07); border-color:rgba(55,214,127,.22); }}
  .gc.cold {{ background:rgba(248,113,107,.06); border-color:rgba(248,113,107,.20); }}
  .gc.r .gcl {{ color:#7aa2e3; }}
  .gcl {{ color:#59606d; font-size:8.5px; font-weight:700; letter-spacing:.05em; }}
  .gcv {{ font-size:13.5px; font-weight:800; font-variant-numeric:tabular-nums; color:#dbe2ec; }}
  .gc.hot .gcv {{ color:#7fe0ac; }} .gc.cold .gcv {{ color:#f0928c; }} .gcv.dim {{ color:#3b4452; }}
  .gcs {{ color:#5c6572; font-size:9.5px; font-weight:600; font-variant-numeric:tabular-nums; }}
  .pctx {{ color:#67707f; font-size:11px; font-weight:500; margin:8px 1px 3px; }}
  .prungs {{ display:flex; flex-wrap:wrap; gap:6px; align-items:center; margin:7px 1px 2px; }}
  .rlbl {{ color:#5c6572; font-size:9.5px; font-weight:700; text-transform:uppercase; letter-spacing:.05em; }}
  .rung {{ background:#161d29; border:1px solid #263041; border-radius:6px; padding:2px 7px; font-size:12px; color:#98a4b5; font-variant-numeric:tabular-nums; }}
  .rung b {{ color:#c9d2de; font-weight:700; }} .rung .ro {{ color:#6ba3f5; font-weight:700; }}
  .cdrv {{ color:#98a4b5; font-weight:600; }}
  .cdvp.soft {{ color:#79b598; }} .cdvp.tough {{ color:#d9a05f; }}
  .bars {{ display:none; padding:20px 2px 4px; }}
  .bars.open {{ display:block; }}
  .chart {{ position:relative; display:flex; gap:5px; height:88px; overflow:visible; }}
  .col {{ flex:1; display:flex; flex-direction:column; align-items:center; justify-content:flex-end; position:relative; }}
  .b {{ width:100%; max-width:26px; border-radius:4px 4px 0 0; position:relative; min-height:3px; z-index:1; }}
  .b.o {{ background:#2f9e63; }}
  .b.u {{ background:#8a3b46; }}
  .bv {{ position:absolute; top:-15px; left:0; right:0; text-align:center; font-size:10.5px; color:#aab3c1; }}
  .m {{ position:absolute; bottom:0; left:0; right:0; background:#222b38; border-radius:3px 3px 0 0; z-index:0; }}
  .mv {{ position:absolute; top:2px; left:0; right:0; text-align:center; font-size:9.5px; font-weight:600; color:#8b94a3; }}
  .why {{ color:#9aa3b2; font-size:12.5px; line-height:1.55; margin:0 2px 14px; }}
  .why b {{ color:#d3dae4; font-weight:700; }}
  .opps {{ display:flex; gap:5px; margin-top:5px; }}
  .opps span {{ flex:1; text-align:center; font-size:9.5px; color:#6b7484; }}
  .pline {{ position:absolute; left:0; right:0; height:0; border-top:1.5px dashed #5b9dff88; z-index:2; }}
  .pline span {{ position:absolute; right:0; top:-8px; font-size:9.5px; color:#5b9dff; background:#08090c; padding:0 3px; }}
  .bnote {{ color:#7d8696; font-size:11.5px; margin-top:9px; text-align:center; }}
  .regime {{ margin:10px 0 4px; padding:9px 11px; background:#141c28; border:1px solid #223047; border-radius:8px; }}
.rgh {{ font-size:12px; color:#aab3c1; margin-bottom:7px; }}
.cmps {{ display:flex; flex-wrap:wrap; gap:6px; }}
.cmp {{ font-size:11px; color:#8b94a3; background:#1c2634; border-radius:5px; padding:2px 7px; opacity:.5; }}
.cmp.pr {{ opacity:1; box-shadow:inset 0 0 0 1px #5b9dff66; }}
.cmp b {{ color:#e6ebf2; }}
.sup {{ color:#4ea373; }}
.warn {{ color:#c98a3c; }}
  .nodata {{ color:#6b7484; font-size:12px; padding:8px 0; }}
  .empty {{ color:#93a0b4; background:#121620; border:1px solid #1f2836; border-radius:16px; padding:26px 20px; text-align:center; font-size:15px; }}
  .empty span {{ color:#6b7484; font-size:13px; }}
  .foot {{ color:#525b6a; font-size:11px; text-align:center; margin-top:26px; line-height:1.6; }}
  .tabs {{ display:flex; gap:6px; margin:16px 0 20px; background:#101520; border:1px solid #1f2836;
    border-radius:12px; padding:4px; }}
  .tab {{ flex:1; text-align:center; padding:9px 0; font-size:14px; font-weight:600; color:#8b94a3;
    border-radius:9px; cursor:pointer; }}
  .tab.active {{ background:#1c2534; color:#e8ecf2; }}
  .panel {{ display:block; }}
  .panel.hidden {{ display:none; }}
  .ttlg {{ font-size:13px; font-weight:700; color:#cdd5e0; margin:0 0 10px; }}
  .ttrow {{ padding:10px 0 9px; border-bottom:1px solid #161d28; cursor:pointer; }}
  .ttmain {{ font-size:15px; display:flex; align-items:center; }}
  .ttchev {{ margin-left:auto; color:#404b5e; font-size:19px; transition:transform .15s; }}
  .ttrow:has(+ .ttlad.open) .ttchev {{ transform:rotate(90deg); }}
  .ttsub {{ color:#93a0b4; font-size:12.5px; margin-top:3px; }}
  .ttside {{ color:#5b9dff; font-weight:700; }}
  .ttbook {{ color:#8ae0b0; font-weight:700; font-variant-numeric:tabular-nums; }}
  .ttlad {{ display:none; padding:6px 0 12px; }}
  .ttlad.open {{ display:block; }}
  .ttlad:last-child {{ border-bottom:0; }}
  .ladhead, .ladrow {{ display:grid; grid-template-columns:56px 1fr 36px 38px 46px; gap:9px;
    align-items:center; }}
  .ladod {{ color:#5b9dff; font-weight:700; text-align:right; font-variant-numeric:tabular-nums; }}
  .ladrow .ladod {{ color:#cdd6e4; }}
  .ladhead {{ color:#6b7484; font-size:9.5px; text-transform:uppercase; letter-spacing:.04em;
    padding:4px 6px 6px; }}
  .ladrow {{ padding:5px 6px; border-radius:7px; font-size:12.5px; }}
  .ladrow.mark {{ background:#15263b; box-shadow:inset 2px 0 0 #5b9dff; }}
  .ladrow.mark .ladl {{ color:#7aa2e3; }}
  .ladrow.dim {{ opacity:.34; }}
  .ladl {{ color:#aeb8c7; font-weight:700; font-variant-numeric:tabular-nums; }}
  .ladm {{ color:#5b9dff; font-size:10px; }}
  .ladbar {{ display:flex; height:7px; border-radius:4px; overflow:hidden; background:#0f141d; }}
  .ladbar i {{ background:#2f9e63; }}
  .ladv {{ text-align:right; font-variant-numeric:tabular-nums; font-weight:600; font-size:12px;
    color:#cdd5e0; }}
  .ladr {{ text-align:right; color:#7d8696; font-size:11px; font-variant-numeric:tabular-nums; }}
  .ladnote {{ color:#5a6474; font-size:10.5px; margin-top:9px; padding:0 6px; }}
  .tcard {{ background:#0f1116; border:1px solid #191d26; border-radius:14px; padding:16px 15px; margin-bottom:11px; }}
  .thead {{ font-size:15px; font-weight:800; margin-bottom:13px; }}
  .trow {{ display:grid; grid-template-columns:repeat(3,1fr); gap:8px; }}
  .tbox {{ text-align:center; background:#080a0e; border:1px solid #171c26; border-radius:9px; padding:9px 4px; }}
  .tk {{ color:#59606d; font-size:9px; text-transform:uppercase; letter-spacing:.05em; font-weight:700; margin-bottom:5px; }}
  .tv {{ font-size:22px; font-weight:800; line-height:1; font-variant-numeric:tabular-nums; }}
  .tv.up {{ color:#37d67f; }} .tv.down {{ color:#f8716b; }}
  .tsub {{ color:#7d8696; font-size:11.5px; text-align:center; margin-top:12px; }}
</style></head><body><div class="wrap">
  <header>
    <h1>Today's Plays</h1>
    <div class="live"><span class="dot"></span>Updated {now:%-I:%M %p} MT · self-refreshing</div>
  </header>
  <div class="tabs">
    <div class="tab active" data-tab="wnba" onclick="showTab('wnba')">🏀 WNBA</div>
    <div class="tab" data-tab="tt" onclick="showTab('tt')">🏓 TT</div>
    <div class="tab" data-tab="tracker" onclick="showTab('tracker')">📊 Tracker</div>
  </div>
  <div class="panel" id="wnba">
    <h2>{pend} plays · grouped by game · tap any bet for the game log</h2>
    <div class="fbar">
      <div class="fgrp" data-f="side">
        <span class="pill on" data-v="all" onclick="setF('side','all')">All</span>
        <span class="pill" data-v="over" onclick="setF('side','over')">Overs</span>
        <span class="pill" data-v="under" onclick="setF('side','under')">Unders</span>
      </div>
      <div class="fgrp" data-f="sort">
        <span class="pill on" data-v="edge" onclick="setF('sort','edge')">Edge</span>
        <span class="pill" data-v="time" onclick="setF('sort','time')">Time</span>
      </div>
    </div>
    <div id="games">{cards}</div>
    {openers_html}
    {wl_html}
  </div>
  <div class="panel hidden" id="tt">
    <h2>Table tennis · by league &amp; game time</h2>
    {tt_html}
  </div>
  <div class="panel hidden" id="tracker">
    <h2>Live record · settles as each event ends</h2>
    {tracker_html}
  </div>
  <div class="foot">Auto-generated on GitHub · self-refreshing · quarter-Kelly unit sizing</div>
</div>
<script>
  function showTab(t) {{
    document.querySelectorAll('.panel').forEach(p => p.classList.toggle('hidden', p.id !== t));
    document.querySelectorAll('.tab').forEach(b => b.classList.toggle('active', b.dataset.tab === t));
    try {{ localStorage.setItem('tab', t); }} catch (e) {{}}
  }}
  try {{ const s = localStorage.getItem('tab'); if (s) showTab(s); }} catch (e) {{}}
  // WNBA filter (over/under) + sort (edge/time) — pure client-side over the server-rendered games
  const F = {{ side:'all', sort:'edge' }};
  function applyF() {{
    document.querySelectorAll('.prop').forEach(p =>
      p.style.display = (F.side==='all' || p.dataset.side===F.side) ? '' : 'none');
    document.querySelectorAll('.pblk').forEach(b =>
      b.style.display = [...b.querySelectorAll('.prop')].some(p => p.style.display!=='none') ? '' : 'none');
    document.querySelectorAll('.game').forEach(g =>
      g.style.display = [...g.querySelectorAll('.pblk')].some(b => b.style.display!=='none') ? '' : 'none');
    const wrap = document.getElementById('games');
    if (wrap) [...wrap.children].sort((a,b) => F.sort==='time'
        ? (a.dataset.tip-b.dataset.tip) : (b.dataset.edge-a.dataset.edge)).forEach(g => wrap.appendChild(g));
  }}
  function setF(k,v) {{
    F[k]=v;
    document.querySelectorAll(`[data-f="${{k}}"] .pill`).forEach(p => p.classList.toggle('on', p.dataset.v===v));
    applyF();
  }}
  // Background refresh: fetch the freshly-built page every 90s and swap ONLY the panels whose
  // data changed — no full reload, so scroll position, expanded ladders, active tab and filters
  // all survive untouched unless there's genuinely new data. Replaces the old <meta refresh>.
  async function bgRefresh() {{
    try {{
      const r = await fetch(location.pathname + '?_=' + Date.now(), {{ cache: 'no-store' }});
      if (!r.ok) return;
      const doc = new DOMParser().parseFromString(await r.text(), 'text/html');
      const y = window.scrollY;
      let touched = false, wnba = false;
      ['wnba','tt','tracker'].forEach(id => {{
        const nw = doc.getElementById(id), cur = document.getElementById(id);
        if (nw && cur && nw.innerHTML !== cur.innerHTML) {{
          cur.innerHTML = nw.innerHTML; touched = true; if (id === 'wnba') wnba = true;
        }}
      }});
      if (wnba) {{   // fresh cards come in server-default order/visibility — restore the user's filter
        document.querySelectorAll('[data-f] .pill').forEach(p => {{
          const g = p.closest('[data-f]').dataset.f;
          p.classList.toggle('on', p.dataset.v === F[g]);
        }});
        applyF();
      }}
      if (touched) window.scrollTo(0, y);
    }} catch (e) {{}}
  }}
  setInterval(bgRefresh, 90000);
</script></body></html>"""
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(doc)
    print(f"dashboard: {len(ordered)} games / {sum(len(g) for g in ordered)} beneficiaries / "
          f"{len(rows)} spots, record {w}-{l} ({u:+.1f}u), {pend} pending -> {OUT}")


if __name__ == "__main__":
    build()
