"""Auto-updating phone dashboard — today's WNBA plays, served free via GitHub Pages.

Reads the injury-autobetter ledger (wnba_ledger.sqlite) and renders a mobile HTML page to
docs/index.html, grouped by beneficiary (team logo + name), sorted most-confident first.
Tap a bet to expand a PropsCash-style bar chart of the player's game-by-game results in
the role, with the line drawn and each game colored over/under. Regenerated by the WNBA
workflows, served by Pages, self-refreshing — current on your phone, no Mac.

    python dashboard.py            # -> docs/index.html
"""
from __future__ import annotations

import datetime as dt
import html
import json
import sqlite3
from collections import defaultdict
from pathlib import Path

try:
    from zoneinfo import ZoneInfo
    MT = ZoneInfo("America/Denver")
except Exception:
    MT = dt.timezone(dt.timedelta(hours=-6))

HERE = Path(__file__).resolve().parent
LEDGER = HERE / "wnba_ledger.sqlite"
OUT = HERE / "docs" / "index.html"
STAT = {"points": "PTS", "rebounds": "REB", "assists": "AST"}
STATKEY = {"points": "pts", "rebounds": "reb", "assists": "ast"}
THIN_EV = 0.35
LOGO = "https://a.espncdn.com/i/teamlogos/wnba/500/{}.png"


def _am(dec):
    dec = float(dec)
    return f"+{round((dec-1)*100)}" if dec >= 2 else f"{round(-100/(dec-1))}"


def _short(n):
    p = (n or "").split()
    return f"{p[0][0]}. {p[-1]}" if len(p) >= 2 else (n or "")


def _conf(r):
    """Confidence = how reliably the projection clears the line: hit rate shrunk toward 50%
    by sample size (odds-INDEPENDENT — price is value, not confidence)."""
    ph, n = r["proj_hit"], r["n_elev"]
    if ph is None or not n:
        return 0.0
    return (ph * n + 0.5 * 6) / (n + 6)


def _load(mt_date):
    if not LEDGER.exists():
        return [], (0, 0, 0.0, 0)
    con = sqlite3.connect(LEDGER)
    con.row_factory = sqlite3.Row
    rows = [dict(r) for r in con.execute(
        "SELECT * FROM predictions WHERE pred_date=? ORDER BY ev DESC", (mt_date,))]
    g = con.execute("SELECT result,odds FROM predictions WHERE graded=1 "
                    "AND pred_date>='2026-07-09'").fetchall()
    con.close()
    dec = [r for r in g if r[0] in ("over", "under")]
    w = sum(1 for r in dec if r[0] == "over")
    u = sum((r[1] - 1) if r[0] == "over" else -1 for r in dec)
    pend = sum(1 for r in rows if r["result"] is None)
    return rows, (w, len(dec) - w, u, pend)


def _bars(r):
    """PropsCash-style game log: vertical bars (oldest->newest), the line drawn across,
    each game green if over / red if under, opponent under each bar."""
    try:
        s = json.loads(r["samples"]) if r["samples"] else []
    except (ValueError, TypeError):
        s = []
    if not s:
        return '<div class="nodata">no game data</div>'
    s = list(reversed(s))                              # stored newest-first -> show oldest-left
    line = float(r["line"])
    vals = [x[0] for x in s]
    mx = max(max(vals), line) * 1.14 or 1
    over = sum(1 for v in vals if v > line)
    note = ("elevated-role games" if r["basis"] == "elevated"
            else f"projected to ~{r['proj_min']:.0f} min")
    cols = "".join(
        f'<div class="col"><div class="b {"o" if v > line else "u"}" style="height:{v/mx*100:.0f}%">'
        f'<span class="bv">{v:g}</span></div><span class="bo">{html.escape(str(opp) or "")}</span></div>'
        for v, opp, *_ in s)
    return (f'<div class="bars"><div class="chart">'
            f'<div class="pline" style="bottom:{line/mx*100:.0f}%"><span>{line:g}</span></div>'
            f'{cols}</div>'
            f'<div class="bnote">{over}/{len(s)} over {line:g} · {note}</div></div>')


def _mkt_row(r):
    stat = STAT.get(r["stat"], r["stat"].upper())
    res, actual = r["result"], r["actual"]
    if res == "over":
        badge, cls = f"HIT {actual:g}", "hit"
    elif res == "under":
        badge, cls = f"miss {actual:g}", "miss"
    elif res == "push":
        badge, cls = f"push {actual:g}", "pend"
    else:
        badge, cls = "•", "pend"
    thin = ' <span class="thin">thin</span>' if float(r["ev"]) > THIN_EV else ""
    proj, n, ph = r["elev_avg"], r["n_elev"], r["proj_hit"]
    if ph is not None and n:
        overs = round(ph * n)
        mid = f'proj {proj:g} · <b>{overs}-{n-overs}</b> ({ph*100:.0f}%){thin}'
    else:
        mid = f'proj {proj:g}{thin}'
    return f"""
      <div class="mkt {cls}" onclick="this.nextElementSibling.classList.toggle('open')">
        <div class="mline"><span class="ms">{stat}</span> o{r['line']:g}
          <span class="mo">{_am(r['odds'])}</span></div>
        <div class="mmid">{mid}</div>
        <div class="mbadge {cls}">{html.escape(badge)}</div>
        <div class="chev">›</div>
      </div>{_bars(r)}"""


def _player_card(player, rows):
    outs = ", ".join(sorted({_short(r["out_player"]) for r in rows}))
    r0 = rows[0]
    team = (r0.get("team") or "").lower()
    logo = (f'<img class="logo" src="{LOGO.format(team)}" alt="" '
            f'onerror="this.style.display=\'none\'">' if team else "")
    ctx = []
    if r0.get("proj_min"):
        dm = f" ({r0['d_min']:+g})" if r0.get("d_min") is not None else ""
        ctx.append(f"~{r0['proj_min']:.0f} min{dm}")
    if r0.get("total"):
        ctx.append(f"O/U {r0['total']:g}")
    if r0.get("opp_def"):
        ctx.append(f"opp allows {r0['opp_def']:g}")
    mkts = "".join(_mkt_row(r) for r in sorted(rows, key=lambda r: -_conf(r)))
    return f"""
    <div class="card">
      <div class="chead">
        <div class="cname">{logo}{html.escape(_short(player))}</div>
        <div class="ctag">{html.escape(outs)} out</div>
      </div>
      <div class="cctx">{' · '.join(html.escape(c) for c in ctx)}</div>
      {mkts}
    </div>"""


def build():
    now = dt.datetime.now(dt.timezone.utc).astimezone(MT)
    rows, (w, l, u, pend) = _load(now.date().isoformat())
    groups = defaultdict(list)
    for r in rows:
        groups[r["player"]].append(r)
    order = sorted(groups.items(), key=lambda kv: -max(_conf(r) for r in kv[1]))
    cards = "\n".join(_player_card(p, rs) for p, rs in order) if order else \
        '<div class="empty">No plays flagged yet.<br><span>The watcher checks every ~60s and fills this in the moment a key player is ruled out.</span></div>'
    rec = f"{w}‑{l}" if (w + l) else "0‑0"
    units = f"{u:+.1f}u" if (w + l) else "—"
    doc = f"""<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="90"><title>Today's Plays</title>
<style>
  :root {{ color-scheme: dark; }}
  * {{ box-sizing:border-box; -webkit-tap-highlight-color:transparent; }}
  body {{ margin:0; background:#0a0d13; color:#e8ecf2;
    font:16px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; -webkit-font-smoothing:antialiased; }}
  .wrap {{ max-width:600px; margin:0 auto; padding:22px 16px 48px; }}
  h1 {{ font-size:22px; font-weight:700; margin:0; letter-spacing:-.01em; }}
  .live {{ display:flex; align-items:center; gap:6px; color:#8b94a3; font-size:12.5px; margin-top:5px; }}
  .dot {{ width:7px; height:7px; border-radius:50%; background:#22c55e; box-shadow:0 0 0 3px #22c55e22; }}
  .stats {{ display:grid; grid-template-columns:repeat(3,1fr); gap:10px; margin:16px 0 24px; }}
  .stat {{ background:#121620; border:1px solid #1f2836; border-radius:14px; padding:13px 12px; min-height:74px;
    display:flex; flex-direction:column; justify-content:space-between; }}
  .stat .k {{ color:#7d8696; font-size:10.5px; text-transform:uppercase; letter-spacing:.06em; }}
  .stat .v {{ font-size:21px; font-weight:700; line-height:1; }}
  .stat .sv {{ color:#7d8696; font-size:12px; font-weight:500; }}
  h2 {{ font-size:12px; color:#7d8696; text-transform:uppercase; letter-spacing:.07em; margin:0 0 12px; font-weight:600; }}
  .card {{ background:#121620; border:1px solid #1f2836; border-radius:16px; padding:15px 16px; margin-bottom:14px; }}
  .chead {{ display:flex; justify-content:space-between; align-items:center; gap:10px; }}
  .cname {{ font-size:17px; font-weight:700; display:flex; align-items:center; gap:9px; }}
  .logo {{ width:26px; height:26px; object-fit:contain; }}
  .ctag {{ font-size:11.5px; color:#e0a458; background:#2a1e0f; border-radius:20px; padding:3px 10px; white-space:nowrap; }}
  .cctx {{ color:#93a0b4; font-size:13px; margin-top:6px; padding-bottom:11px; border-bottom:1px solid #1c2431; }}
  .mkt {{ display:flex; align-items:center; gap:10px; padding:12px 0 10px; border-bottom:1px solid #161d28; cursor:pointer; }}
  .mline {{ font-size:15.5px; font-weight:600; min-width:96px; }}
  .ms {{ color:#aeb8c7; font-weight:700; font-size:13px; margin-right:2px; }}
  .mo {{ color:#5b9dff; font-weight:700; }}
  .mmid {{ flex:1; color:#8b94a3; font-size:13px; }}
  .mmid b {{ color:#cdd5e0; font-weight:700; }}
  .thin {{ color:#c99a52; font-size:11px; background:#241c0e; padding:1px 6px; border-radius:6px; margin-left:2px; }}
  .mbadge {{ font-size:11.5px; font-weight:700; padding:4px 9px; border-radius:20px; white-space:nowrap; }}
  .mbadge.pend {{ background:transparent; color:#39435500; font-size:0; }}
  .mbadge.pend::before {{ content:"·"; color:#3c4658; font-size:22px; }}
  .mbadge.hit {{ background:#0e2c1a; color:#4ade80; }}
  .mbadge.miss {{ background:#2a1214; color:#f87171; }}
  .chev {{ color:#404b5e; font-size:20px; transition:transform .15s; }}
  .mkt:has(+ .bars.open) .chev {{ transform:rotate(90deg); }}
  .bars {{ display:none; padding:14px 2px 4px; }}
  .bars.open {{ display:block; }}
  .chart {{ position:relative; display:flex; align-items:flex-end; gap:5px; height:88px; padding-top:16px; }}
  .col {{ flex:1; display:flex; flex-direction:column; align-items:center; height:100%; justify-content:flex-end; }}
  .b {{ width:100%; max-width:26px; border-radius:4px 4px 0 0; position:relative; min-height:3px; }}
  .b.o {{ background:#2f9e63; }}
  .b.u {{ background:#8a3b46; }}
  .bv {{ position:absolute; top:-15px; left:0; right:0; text-align:center; font-size:10.5px; color:#aab3c1; }}
  .bo {{ font-size:9.5px; color:#6b7484; margin-top:4px; }}
  .pline {{ position:absolute; left:0; right:0; height:0; border-top:1.5px dashed #5b9dff88; z-index:2; }}
  .pline span {{ position:absolute; right:0; top:-8px; font-size:9.5px; color:#5b9dff; background:#0a0d13; padding:0 3px; }}
  .bnote {{ color:#7d8696; font-size:11.5px; margin-top:9px; text-align:center; }}
  .nodata {{ color:#6b7484; font-size:12px; padding:8px 0; }}
  .empty {{ color:#93a0b4; background:#121620; border:1px solid #1f2836; border-radius:16px; padding:26px 20px; text-align:center; font-size:15px; }}
  .empty span {{ color:#6b7484; font-size:13px; }}
  .foot {{ color:#525b6a; font-size:11px; text-align:center; margin-top:26px; line-height:1.6; }}
</style></head><body><div class="wrap">
  <header>
    <h1>Today's Plays</h1>
    <div class="live"><span class="dot"></span>Updated {now:%-I:%M %p} MT · tap a bet for the game log</div>
  </header>
  <div class="stats">
    <div class="stat"><div class="k">Board</div><div class="v">{len(order)}<span class="sv"> player{'s' if len(order)!=1 else ''}</span></div></div>
    <div class="stat"><div class="k">Record · 7/9</div><div class="v">{rec}<div class="sv">{units}</div></div></div>
    <div class="stat"><div class="k">Pending</div><div class="v">{pend}</div></div>
  </div>
  <h2>Beneficiaries</h2>
  {cards}
  <div class="foot">Auto-generated on GitHub · self-refreshing · tap a bet to see the bars<br>proj = production in the elevated role · thin = small sample</div>
</div></body></html>"""
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(doc)
    print(f"dashboard: {len(order)} beneficiaries / {len(rows)} spots, record {rec}, {pend} pending -> {OUT}")


if __name__ == "__main__":
    build()
