"""Auto-updating phone dashboard — today's WNBA plays, served free via GitHub Pages.

Reads the injury-autobetter ledger (wnba_ledger.sqlite) and renders a mobile HTML page to
docs/index.html, grouped by beneficiary (team logo + name), sorted most-confident first.
Tap a bet to expand a PropsCash-style bar chart of the player's game-by-game results in
the role, with the line drawn and each game colored over/under. Regenerated by the WNBA
workflows, served by Pages, self-refreshing — current on your phone, no Mac.

    python dashboard.py            # -> docs/index.html
"""
from __future__ import annotations

import datetime as dt
import html
import json
import sqlite3
from collections import defaultdict
from pathlib import Path

import requests

try:
    from zoneinfo import ZoneInfo
    MT = ZoneInfo("America/Denver")
except Exception:
    MT = dt.timezone(dt.timedelta(hours=-6))

HERE = Path(__file__).resolve().parent
LEDGER = HERE / "wnba_ledger.sqlite"
OUT = HERE / "docs" / "index.html"
STAT = {"points": "PTS", "rebounds": "REB", "assists": "AST"}
STATKEY = {"points": "pts", "rebounds": "reb", "assists": "ast"}
THIN_EV = 0.35
LOGO = "https://a.espncdn.com/i/teamlogos/wnba/500/{}.png"


def _am(dec):
    dec = float(dec)
    return f"+{round((dec-1)*100)}" if dec >= 2 else f"{round(-100/(dec-1))}"


def _short(n):
    p = (n or "").split()
    return f"{p[0][0]}. {p[-1]}" if len(p) >= 2 else (n or "")


def _conf(r):
    """Confidence = how reliably the projection clears the line: hit rate shrunk toward 50%
    by sample size (odds-INDEPENDENT — price is value, not confidence)."""
    ph, n = r["proj_hit"], r["n_elev"]
    if ph is None or not n:
        return 0.0
    return (ph * n + 0.5 * 6) / (n + 6)


def _units(dec):
    """Recommended stake by ODDS (risk control), NOT model edge. Quarter-Kelly was wrong here:
    it sized UP the longshots the model liked — but the model's edge on longshots is exactly
    what's least reliable (every +240 alt-line busted the first slate). So: flat 1u through
    +100, then lower the longer the price. ~0.7u @ +150, 0.5u @ +200, 0.4u @ +240, 0.3u @
    +300, 0.25u floor."""
    dec = float(dec)
    if dec <= 2.0:                              # -inf .. +100 (favorites through pick'em): base
        return 1.0
    return max(0.25, round((2.0 / dec) ** 1.7 / 0.05) * 0.05)


def _tip_times():
    """{team_abbr: tip_datetime_utc} for today's slate from ESPN, so cards can be ordered
    by game time and show it."""
    et = dt.datetime.now(dt.timezone.utc).astimezone(dt.timezone(dt.timedelta(hours=-4))).strftime("%Y%m%d")
    try:
        j = requests.get(
            f"https://site.api.espn.com/apis/site/v2/sports/basketball/wnba/scoreboard?dates={et}",
            headers={"User-Agent": "Mozilla/5.0"}, timeout=15).json()
    except requests.RequestException:
        return {}
    out = {}
    for e in j.get("events", []):
        try:
            tip = dt.datetime.fromisoformat((e.get("date") or "").replace("Z", "+00:00"))
        except ValueError:
            continue
        for c in e.get("competitions", [{}])[0].get("competitors", []):
            ab = c.get("team", {}).get("abbreviation")
            if ab:
                out[ab] = tip
    return out


def _load(mt_date):
    if not LEDGER.exists():
        return [], (0, 0, 0.0, 0)
    con = sqlite3.connect(LEDGER)
    con.row_factory = sqlite3.Row
    # BOARD shows only un-settled bets — a bet drops off the moment it grades (its result
    # then lives in the Tracker record, below).
    rows = [dict(r) for r in con.execute(
        "SELECT * FROM predictions WHERE pred_date=? AND result IS NULL ORDER BY ev DESC",
        (mt_date,))]
    g = con.execute("SELECT result,odds FROM predictions WHERE graded=1 "
                    "AND pred_date>='2026-07-09'").fetchall()
    con.close()
    # durable user-played marks (wnba_played.txt) — read-only, so the ✓ shows on the board
    # independent of when CI last synced the DB column
    pf = HERE / "wnba_played.txt"
    if pf.exists():
        marks = [ln.split("|") for ln in pf.read_text().splitlines() if ln.count("|") == 3]
        for r in rows:
            if any(d == r["pred_date"] and s == r["stat"] and pl.lower() in (r["player"] or "").lower()
                   and abs((r["line"] or 0) - float(ln)) < 1e-9 for d, pl, s, ln in marks):
                r["played"] = 1
    dec = [r for r in g if r[0] in ("over", "under")]
    w = sum(1 for r in dec if r[0] == "over")
    # P&L weighted by the recommended (odds-based) stake, so the tracker reflects how the
    # plays are actually sized — a losing +240 longshot costs its 0.35u, not a flat 1u.
    u = sum(_units(r[1]) * (r[1] - 1) if r[0] == "over" else -_units(r[1]) for r in dec)
    return rows, (w, len(dec) - w, u, len(rows))


def _bars(r):
    """PropsCash-style game log: vertical bars (oldest->newest), the line drawn across,
    each game green if over / red if under, opponent under each bar."""
    try:
        s = json.loads(r["samples"]) if r["samples"] else []
    except (ValueError, TypeError):
        s = []
    if not s:
        return '<div class="nodata">no game data</div>'
    s = list(reversed(s))                              # stored newest-first -> show oldest-left
    line = float(r["line"])
    vals = [x[0] for x in s]
    mx = max(max(vals), line) * 1.14 or 1
    over = sum(1 for v in vals if v > line)
    note = ("elevated-role games" if r["basis"] == "elevated"
            else f"projected to ~{r['proj_min']:.0f} min")
    # bars (baseline = chart bottom) and opponent labels are SEPARATE rows, so the bars and
    # the prop line share one baseline + scale.
    bars = "".join(
        f'<div class="col"><div class="b {"o" if v > line else "u"}" style="height:{v/mx*100:.1f}%">'
        f'<span class="bv">{v:g}</span></div></div>' for v, *_ in s)
    opps = "".join(f'<span>{html.escape(str(o) or "")}</span>' for _, o, *_ in s)
    return (f'<div class="bars"><div class="chart">'
            f'<div class="pline" style="bottom:{line/mx*100:.1f}%"><span>{line:g}</span></div>'
            f'{bars}</div><div class="opps">{opps}</div>'
            f'<div class="bnote">{over}/{len(s)} over {line:g} · {note}</div></div>')


def _mkt_row(r):
    stat = STAT.get(r["stat"], r["stat"].upper())
    res, actual = r["result"], r["actual"]
    if res == "over":
        badge, cls = f"HIT {actual:g}", "hit"
    elif res == "under":
        badge, cls = f"miss {actual:g}", "miss"
    elif res == "push":
        badge, cls = f"push {actual:g}", "pend"
    else:
        badge, cls = "•", "pend"
    proj, n, ph = r["elev_avg"], r["n_elev"], r["proj_hit"]
    if ph is not None and n:
        overs = round(ph * n)
        mid = f'proj {proj:g} · <b>{overs}-{n-overs}</b> ({ph*100:.0f}%)'
    else:
        mid = f'proj {proj:g}'
    # injury-driven boost for this stat (usage rise for pts, reb/ast rise otherwise) — the
    # tell for a role-inheritor vs a maxed-out star who plays the same (Copper: +0.6).
    drv = r.get("driver")
    if drv is not None:
        lbl = {"points": "usg", "rebounds": "reb", "assists": "ast"}.get(r["stat"], "")
        if drv < 1:
            mid += ' · <span class="drv none">baseline</span>'
        else:
            mid += f' · <span class="drv {"big" if drv >= 3 else ""}">▲{drv:+.0f} {lbl}</span>'
    u = _units(float(r["odds"]))
    juice = ' <span class="juice">⚠ juice</span>' if float(r["odds"]) < 1.50 else ''  # worse than -200
    played = ' <span class="played">✓</span>' if r.get("played") else ''
    return f"""
      <div class="mkt {cls}" onclick="this.nextElementSibling.classList.toggle('open')">
        <div class="mline"><span class="ms">{stat}</span> o{r['line']:g}
          <span class="mo">{_am(r['odds'])}</span>{juice} <span class="mu">{u:g}u</span>{played}</div>
        <div class="mmid">{mid}</div>
        <div class="mbadge {cls}">{html.escape(badge)}</div>
        <div class="chev">›</div>
      </div>{_bars(r)}"""


def _player_card(player, rows, tip=None):
    outs = ", ".join(sorted({_short(r["out_player"]) for r in rows}))
    r0 = rows[0]
    team = (r0.get("team") or "").upper()
    logo = (f'<img class="logo" src="{LOGO.format(team.lower())}" alt="" '
            f'onerror="this.style.display=\'none\'">' if team else "")
    when = tip.astimezone(MT).strftime("%-I:%M %p") if tip else ""
    game = " · ".join(x for x in (f"{team} vs {r0['opp']}" if r0.get("opp") else team,
                                  f"{when} MT" if when else "") if x)
    cb = {"confirmed": ("✓ starting", "cok"), "bench": ("not starting", "cbad"),
          "likely": ("likely starts", "cmid"), "projected": ("lineup TBD", "cmid")}.get(
              r0.get("confidence") or "projected", ("", ""))
    conf_html = f'<span class="cconf {cb[1]}">{cb[0]}</span>' if cb[0] else ""
    ctx = []
    if r0.get("total"):
        ctx.append(f"O/U {r0['total']:g}")
    if r0.get("opp_def"):
        ctx.append(f"opp allows {r0['opp_def']:g}")
    # role-jump badge: minutes gained without the out player = the clearest "did the role
    # actually change" — a role-inheritor jumps (Ayayi +17), a maxed-out star barely moves
    # (Copper +3). Green when it's a real jump, muted when it isn't.
    role = ""
    if r0.get("proj_min"):
        dm = r0.get("d_min")
        if dm is not None:
            jcls = "jbig" if dm >= 6 else ("jnone" if dm < 3 else "")
            role = f'<span class="jump {jcls}">~{r0["proj_min"]:.0f} min · ▲{dm:+.0f} role</span>'
        else:
            role = f'<span class="jump">~{r0["proj_min"]:.0f} min</span>'
    ctxtext = ' · '.join(html.escape(c) for c in ctx)
    cctx = role + (f' · {ctxtext}' if ctxtext else "")
    mkts = "".join(_mkt_row(r) for r in sorted(rows, key=lambda r: -_conf(r)))
    return f"""
    <div class="card">
      <div class="chead">
        <div class="cname">{logo}{html.escape(_short(player))}</div>
        <div class="ctag">{html.escape(outs)} out</div>
      </div>
      <div class="cgame">{html.escape(game)}{conf_html}</div>
      <div class="cctx">{cctx}</div>
      {mkts}
    </div>"""


def _load_tt():
    f = HERE / "tt_board.json"
    if not f.exists():
        return None
    try:
        return json.loads(f.read_text())
    except (ValueError, OSError):
        return None


def _tracker_panel(wnba_rec, tt_json):
    """Tracker tab — live record / hit rate / units for WNBA and Table Tennis, flat 1u,
    updated as each event settles."""
    def card(emoji, title, w, l, u, note):
        n = w + l
        hit = f"{w/n*100:.0f}%" if n else "—"
        roi = f"{u/n*100:+.0f}%" if n else ""
        ucls = "up" if u > 0 else ("down" if u < 0 else "")
        return f"""
      <div class="tcard">
        <div class="thead">{emoji} {html.escape(title)}</div>
        <div class="trow">
          <div class="tbox"><div class="tk">Record</div><div class="tv">{w}-{l}</div></div>
          <div class="tbox"><div class="tk">Hit rate</div><div class="tv">{hit}</div></div>
          <div class="tbox"><div class="tk">Units</div><div class="tv {ucls}">{u:+.1f}u</div></div>
        </div>
        <div class="tsub">{html.escape(note)}{(' · ROI ' + roi) if roi else ''}</div>
      </div>"""
    w, l, u = wnba_rec
    out = card("🏀", "WNBA injury props", w, l, u, "flat 1u · settles live · since 7/9")
    tt = (tt_json or {}).get("tracker")
    if tt:
        out += card("🏓", "Table tennis", tt.get("w", 0), tt.get("l", 0), tt.get("u", 0.0),
                    "flat 1u · settles live · since 7/9")
    else:
        out += ('<div class="tcard"><div class="thead">🏓 Table tennis</div>'
                '<div class="tsub">connecting… (needs the tt-elite bridge)</div></div>')
    return out


def _tt_ladder(lad, play_to, zone):
    """Tap-to-expand hit-rate ladder: the raw H2H hit rate of the FLAGGED SIDE at every line
    a book might post (70.5–80.5), so the user reads the rate at THEIR exact line. Over bet
    -> over% per line; under bet -> under% per line. The ◄ marks the furthest line still
    worth playing (the model's validated cutoff); rows PAST that edge are dimmed = skip."""
    if not lad:
        return '<div class="ttlad"><div class="ladnote">no H2H line ladder</div></div>'
    over_side = zone.startswith("O")
    sidelbl = "over" if over_side else "under"
    rows = ""
    for r in lad:
        pct = r["op"] if over_side else 100 - r["op"]
        hit = r["o"] if over_side else r["u"]
        miss = r["u"] if over_side else r["o"]
        edge = abs(r["line"] - play_to) < 0.01
        noplay = (r["line"] > play_to) if over_side else (r["line"] < play_to)
        cls = " mark" if edge else (" dim" if noplay else "")
        lbl = f'{r["line"]:g}' + (' <span class="ladm">◄</span>' if edge else "")
        rows += (f'<div class="ladrow{cls}">'
                 f'<span class="ladl">{lbl}</span>'
                 f'<span class="ladbar"><i style="width:{pct}%"></i></span>'
                 f'<span class="ladv">{pct}%</span>'
                 f'<span class="ladr">{hit}-{miss}</span></div>')
    return (f'<div class="ttlad">'
            f'<div class="ladhead"><span>Line</span><span>{sidelbl} hit rate</span>'
            f'<span class="ladv">%</span><span class="ladr">rec</span></div>'
            f'{rows}'
            f'<div class="ladnote">◄ play {sidelbl} up to here · dimmed rows = edge too thin, skip</div></div>')


def _tt_panel(data):
    """Table Tennis tab — today's flagged bets, grouped by league, ordered by game time.
    Each matchup taps open to a per-line hit-rate ladder."""
    if not data:
        return ('<div class="empty">Table tennis feed connecting…<br>'
                '<span>Once the tt-elite bridge is set up, today\'s TT bets show here.</span></div>')
    bets = data.get("bets", [])
    if not bets:
        return ('<div class="empty">No TT bets flagged right now.<br>'
                '<span>Fixtures post a few hours before play — check back closer to the slate.</span></div>')
    default_line = data.get("model_line", 74.5)
    by = defaultdict(list)
    for b in bets:
        by[b["league"]].append(b)
    out = []
    for league in sorted(by):
        games = sorted(by[league], key=lambda b: b.get("ts") or 0)
        cards = ""
        for b in games:
            when = (dt.datetime.fromtimestamp(b["ts"], MT).strftime("%-I:%M %p")
                    if b.get("ts") else "TBD")
            side = html.escape(b.get("side", ""))
            lad = _tt_ladder(b.get("ladder", []), b.get("play_to", default_line), b.get("side", ""))
            cards += f"""
      <div class="ttrow" onclick="this.nextElementSibling.classList.toggle('open')">
        <div class="ttmain"><b>{html.escape(b['p1'])}</b> v {html.escape(b['p2'])}<span class="ttchev">›</span></div>
        <div class="ttsub">{when} MT · <span class="ttside">{side}</span> · {b['rec']} ({b['raw']}%) · {b['u']:g}u</div>
      </div>{lad}"""
        out.append(f'<div class="card"><h3 class="ttlg">{html.escape(league)}</h3>{cards}</div>')
    return "\n".join(out)


def build():
    now = dt.datetime.now(dt.timezone.utc).astimezone(MT)
    rows, (w, l, u, pend) = _load(now.date().isoformat())
    tips = _tip_times()
    groups = defaultdict(list)
    for r in rows:
        groups[r["player"]].append(r)
    # primary: game tip time (earliest first); secondary: most-confident play first
    def _key(kv):
        t = tips.get((kv[1][0].get("team") or "").upper())
        return (t.timestamp() if t else 9e18, -max(_conf(r) for r in kv[1]))
    order = sorted(groups.items(), key=_key)
    cards = "\n".join(_player_card(p, rs, tips.get((rs[0].get("team") or "").upper()))
                      for p, rs in order) if order else \
        '<div class="empty">No plays flagged yet.<br><span>The watcher checks every ~60s and fills this in the moment a key player is ruled out.</span></div>'
    tt_json = _load_tt()
    tt_html = _tt_panel(tt_json)
    tracker_html = _tracker_panel((w, l, u), tt_json)
    doc = f"""<!doctype html><html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="90"><title>Today's Plays</title>
<style>
  :root {{ color-scheme: dark; }}
  * {{ box-sizing:border-box; -webkit-tap-highlight-color:transparent; }}
  body {{ margin:0; background:#0a0d13; color:#e8ecf2;
    font:16px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; -webkit-font-smoothing:antialiased; }}
  .wrap {{ max-width:600px; margin:0 auto; padding:22px 16px 48px; }}
  h1 {{ font-size:22px; font-weight:700; margin:0; letter-spacing:-.01em; }}
  .live {{ display:flex; align-items:center; gap:6px; color:#8b94a3; font-size:12.5px; margin-top:5px; }}
  .dot {{ width:7px; height:7px; border-radius:50%; background:#22c55e; box-shadow:0 0 0 3px #22c55e22; }}
  .stats {{ display:grid; grid-template-columns:repeat(3,1fr); gap:10px; margin:16px 0 24px; }}
  .stat {{ background:#121620; border:1px solid #1f2836; border-radius:14px; padding:13px 12px; min-height:74px;
    display:flex; flex-direction:column; justify-content:space-between; }}
  .stat .k {{ color:#7d8696; font-size:10.5px; text-transform:uppercase; letter-spacing:.06em; }}
  .stat .v {{ font-size:21px; font-weight:700; line-height:1; }}
  .stat .sv {{ color:#7d8696; font-size:12px; font-weight:500; }}
  h2 {{ font-size:12px; color:#7d8696; text-transform:uppercase; letter-spacing:.07em; margin:0 0 12px; font-weight:600; }}
  .card {{ background:#121620; border:1px solid #1f2836; border-radius:16px; padding:15px 16px; margin-bottom:14px; }}
  .chead {{ display:flex; justify-content:space-between; align-items:center; gap:10px; }}
  .cname {{ font-size:17px; font-weight:700; display:flex; align-items:center; gap:9px; }}
  .logo {{ width:26px; height:26px; object-fit:contain; }}
  .ctag {{ font-size:11.5px; color:#e0a458; background:#2a1e0f; border-radius:20px; padding:3px 10px; white-space:nowrap; }}
  .cgame {{ color:#c3cbd8; font-size:12.5px; font-weight:600; margin-top:7px; }}
  .cconf {{ font-size:10.5px; font-weight:700; padding:2px 7px; border-radius:20px; margin-left:7px; white-space:nowrap; }}
  .cconf.cok {{ background:#0e2c1a; color:#4ade80; }}
  .cconf.cbad {{ background:#2a1214; color:#f87171; }}
  .cconf.cmid {{ background:#182234; color:#7aa2e3; }}
  .cctx {{ color:#93a0b4; font-size:13px; margin-top:3px; padding-bottom:11px; border-bottom:1px solid #1c2431; }}
  .mkt {{ display:flex; align-items:center; gap:10px; padding:12px 0 10px; border-bottom:1px solid #161d28; cursor:pointer; }}
  .mline {{ font-size:15.5px; font-weight:600; min-width:96px; }}
  .ms {{ color:#aeb8c7; font-weight:700; font-size:13px; margin-right:2px; }}
  .mo {{ color:#5b9dff; font-weight:700; }}
  .mmid {{ flex:1; color:#8b94a3; font-size:13px; }}
  .mmid b {{ color:#cdd5e0; font-weight:700; }}
  .juice {{ color:#e0a458; font-size:11px; font-weight:700; white-space:nowrap; }}
  .played {{ color:#4ade80; font-size:12.5px; font-weight:800; }}
  .drv {{ font-size:11.5px; color:#8b94a3; }}
  .drv.big {{ color:#5bbd85; font-weight:700; }}
  .drv.none {{ color:#6b7484; }}
  .jump {{ font-size:13px; color:#93a0b4; font-weight:600; }}
  .jump.jbig {{ color:#4ade80; }}
  .jump.jnone {{ color:#7d8696; font-weight:500; }}
  .thin {{ color:#c99a52; font-size:11px; background:#241c0e; padding:1px 6px; border-radius:6px; margin-left:2px; }}
  .mbadge {{ font-size:11.5px; font-weight:700; padding:4px 9px; border-radius:20px; white-space:nowrap; }}
  .mbadge.pend {{ background:transparent; color:#39435500; font-size:0; }}
  .mbadge.pend::before {{ content:"·"; color:#3c4658; font-size:22px; }}
  .mbadge.hit {{ background:#0e2c1a; color:#4ade80; }}
  .mbadge.miss {{ background:#2a1214; color:#f87171; }}
  .chev {{ color:#404b5e; font-size:20px; transition:transform .15s; }}
  .mkt:has(+ .bars.open) .chev {{ transform:rotate(90deg); }}
  .bars {{ display:none; padding:20px 2px 4px; }}
  .bars.open {{ display:block; }}
  .chart {{ position:relative; display:flex; gap:5px; height:88px; overflow:visible; }}
  .col {{ flex:1; display:flex; flex-direction:column; align-items:center; justify-content:flex-end; }}
  .b {{ width:100%; max-width:26px; border-radius:4px 4px 0 0; position:relative; min-height:3px; }}
  .b.o {{ background:#2f9e63; }}
  .b.u {{ background:#8a3b46; }}
  .bv {{ position:absolute; top:-15px; left:0; right:0; text-align:center; font-size:10.5px; color:#aab3c1; }}
  .opps {{ display:flex; gap:5px; margin-top:5px; }}
  .opps span {{ flex:1; text-align:center; font-size:9.5px; color:#6b7484; }}
  .pline {{ position:absolute; left:0; right:0; height:0; border-top:1.5px dashed #5b9dff88; z-index:2; }}
  .pline span {{ position:absolute; right:0; top:-8px; font-size:9.5px; color:#5b9dff; background:#0a0d13; padding:0 3px; }}
  .bnote {{ color:#7d8696; font-size:11.5px; margin-top:9px; text-align:center; }}
  .nodata {{ color:#6b7484; font-size:12px; padding:8px 0; }}
  .empty {{ color:#93a0b4; background:#121620; border:1px solid #1f2836; border-radius:16px; padding:26px 20px; text-align:center; font-size:15px; }}
  .empty span {{ color:#6b7484; font-size:13px; }}
  .foot {{ color:#525b6a; font-size:11px; text-align:center; margin-top:26px; line-height:1.6; }}
  .tabs {{ display:flex; gap:6px; margin:16px 0 20px; background:#101520; border:1px solid #1f2836;
    border-radius:12px; padding:4px; }}
  .tab {{ flex:1; text-align:center; padding:9px 0; font-size:14px; font-weight:600; color:#8b94a3;
    border-radius:9px; cursor:pointer; }}
  .tab.active {{ background:#1c2534; color:#e8ecf2; }}
  .panel {{ display:block; }}
  .panel.hidden {{ display:none; }}
  .ttlg {{ font-size:13px; font-weight:700; color:#cdd5e0; margin:0 0 10px; }}
  .ttrow {{ padding:10px 0 9px; border-bottom:1px solid #161d28; cursor:pointer; }}
  .ttmain {{ font-size:15px; display:flex; align-items:center; }}
  .ttchev {{ margin-left:auto; color:#404b5e; font-size:19px; transition:transform .15s; }}
  .ttrow:has(+ .ttlad.open) .ttchev {{ transform:rotate(90deg); }}
  .ttsub {{ color:#93a0b4; font-size:12.5px; margin-top:3px; }}
  .ttside {{ color:#5b9dff; font-weight:700; }}
  .ttlad {{ display:none; padding:6px 0 12px; }}
  .ttlad.open {{ display:block; }}
  .ttlad:last-child {{ border-bottom:0; }}
  .ladhead, .ladrow {{ display:grid; grid-template-columns:58px 1fr 44px 40px; gap:10px;
    align-items:center; }}
  .ladhead {{ color:#6b7484; font-size:9.5px; text-transform:uppercase; letter-spacing:.04em;
    padding:4px 6px 6px; }}
  .ladrow {{ padding:5px 6px; border-radius:7px; font-size:12.5px; }}
  .ladrow.mark {{ background:#15263b; box-shadow:inset 2px 0 0 #5b9dff; }}
  .ladrow.mark .ladl {{ color:#7aa2e3; }}
  .ladrow.dim {{ opacity:.34; }}
  .ladl {{ color:#aeb8c7; font-weight:700; font-variant-numeric:tabular-nums; }}
  .ladm {{ color:#5b9dff; font-size:10px; }}
  .ladbar {{ display:flex; height:7px; border-radius:4px; overflow:hidden; background:#0f141d; }}
  .ladbar i {{ background:#2f9e63; }}
  .ladv {{ text-align:right; font-variant-numeric:tabular-nums; font-weight:600; font-size:12px;
    color:#cdd5e0; }}
  .ladr {{ text-align:right; color:#7d8696; font-size:11px; font-variant-numeric:tabular-nums; }}
  .ladnote {{ color:#5a6474; font-size:10.5px; margin-top:9px; padding:0 6px; }}
  .mu {{ color:#c99a52; font-weight:700; font-size:13px; margin-left:4px; }}
  .tcard {{ background:#121620; border:1px solid #1f2836; border-radius:16px; padding:18px 16px; margin-bottom:14px; }}
  .thead {{ font-size:16px; font-weight:700; margin-bottom:14px; }}
  .trow {{ display:grid; grid-template-columns:repeat(3,1fr); gap:10px; }}
  .tbox {{ text-align:center; }}
  .tk {{ color:#7d8696; font-size:10.5px; text-transform:uppercase; letter-spacing:.05em; margin-bottom:5px; }}
  .tv {{ font-size:24px; font-weight:800; line-height:1; }}
  .tv.up {{ color:#4ade80; }} .tv.down {{ color:#f87171; }}
  .tsub {{ color:#7d8696; font-size:11.5px; text-align:center; margin-top:14px; }}
</style></head><body><div class="wrap">
  <header>
    <h1>Today's Plays</h1>
    <div class="live"><span class="dot"></span>Updated {now:%-I:%M %p} MT · self-refreshing</div>
  </header>
  <div class="tabs">
    <div class="tab active" data-tab="wnba" onclick="showTab('wnba')">🏀 WNBA</div>
    <div class="tab" data-tab="tt" onclick="showTab('tt')">🏓 TT</div>
    <div class="tab" data-tab="tracker" onclick="showTab('tracker')">📊 Tracker</div>
  </div>
  <div class="panel" id="wnba">
    <h2>{len(order)} beneficiar{'y' if len(order)==1 else 'ies'} · {pend} pending · tap a bet for the game log</h2>
    {cards}
  </div>
  <div class="panel hidden" id="tt">
    <h2>Table tennis · by league &amp; game time</h2>
    {tt_html}
  </div>
  <div class="panel hidden" id="tracker">
    <h2>Live record · settles as each event ends</h2>
    {tracker_html}
  </div>
  <div class="foot">Auto-generated on GitHub · self-refreshing · quarter-Kelly unit sizing</div>
</div>
<script>
  function showTab(t) {{
    document.querySelectorAll('.panel').forEach(p => p.classList.toggle('hidden', p.id !== t));
    document.querySelectorAll('.tab').forEach(b => b.classList.toggle('active', b.dataset.tab === t));
    try {{ localStorage.setItem('tab', t); }} catch (e) {{}}
  }}
  try {{ const s = localStorage.getItem('tab'); if (s) showTab(s); }} catch (e) {{}}
</script></body></html>"""
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(doc)
    print(f"dashboard: {len(order)} beneficiaries / {len(rows)} spots, record {w}-{l} ({u:+.1f}u), {pend} pending -> {OUT}")


if __name__ == "__main__":
    build()
